### ISSUE TITLE
Migrating referencing wrong talbe(using custom user model on Django 1.6.1)

### ISSUE THREAD

**Issue by mnazim** [evonove/django-oauth-toolkit#104]
Migration is referencing table "users_user" table while it should be referencing "users"(which already exists in db)

User Model:

    class User(AbstractUser):
    
        class Meta:
            verbose_name = 'user'
            verbose_name_plural = 'users'
            db_table = 'users'
    

Error in migration:

    $ ./manage.py migrate  oauth2_provider
    Running migrations for oauth2_provider:
     - Migrating forwards to 0001_initial.
     > oauth2_provider:0001_initial
    FATAL ERROR - The following SQL query failed: ALTER TABLE "oauth2_provider_application" ADD CONSTRAINT "user_id_refs_id_ea23d820" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
    The error was: relation "users_user" does not exist.

**Comment by poswald** [comment]
The migrations in this project have been updated since this was opened. Things should be working better now but please create a new ticket if you are still seeing issues.
