### ISSUE TITLE
Redirecting to accounts/login

### ISSUE THREAD

**Issue by aw3s0me** [evonove/django-oauth-toolkit#121]
I have django 1.6, python 3.3 and when i try to do tutorial step /o/applications/ it redirects me to accounts/login/?next=/o/applications/ which is not found. 

Everything is done by your django rest tutorial, but i've changed 1 string from django.conf.urls.defaults import url, patterns, include to from django.conf.urls import url, patterns, include. Cos there is no urls.defaults in 1.6 django.

So what to do?

**Comment by zxkane** [comment]
looks like it's something should be added into doc.
