### ISSUE TITLE
apps with different scopes

### ISSUE THREAD

**Issue by gregbanks** [evonove/django-oauth-toolkit#130]
hi,

i'd like to implement multiple apps with different scopes that will be hitting the same django-oauth-toolkit provider (ex. app1 should just be associated with the "read" scope while app2 should have both the "read" and "write" scope). it appears that all apps are authorized for whatever scopes are in `oauth2_provider.settings.oauth2_settings._SCOPES` via a call into `oauth2_provder.oauth2_validators.OAuth2Validator.get_default_scopes` from oauthlib during the authorization flow.

am i missing something? if i am not, what would be the suggested way to implement the aforementioned functionality? should i extend `oauth2_provider.models.Application` to have a scopes attribute and then override `oauth2_provder.oauth2_validators.OAuth2Validator.get_default_scopes` to query that attribute?

thanks!

cheers,
greg

**Comment by jleclanche** [comment]
The new model-based scopes backends implement this!

**Comment by SinaZK** [comment]
Is this implemented? Can't find it in docs.
