### ISSUE TITLE
Use user.is_active to determine client app

### ISSUE THREAD

**Issue by poswald** [evonove/django-oauth-toolkit#141]
When using the application with the `client_credentials` grant type, it is not clear to me how a provider is supposed to revoke access to a client application. I thought that perhaps the `user.is_active` field would be used but it only seems to be [checked](https://github.com/evonove/django-oauth-toolkit/blob/da56a7bd6ede163bd73e9b36d708bfddaf71b728/oauth2_provider/oauth2_validators.py#L324) in `validate_user` and but doesn't seem to have any effect, at least in this grant type. I also expected `user.last_login` to be updated for OAuth 2 access and it doesn't seem to be.

Is there an official way to revoke or disable a client application such that it is no longer useful for giving out bearer tokens? If you point me in the right direction, I'll try to add some documentation on it. If you agree that `user.is_active` should be used to determine access, can we look into adding that?

**Comment by jleclanche** [comment]
I implemented `Application.is_usable(request)` in `issue/141` which can be overridden to ban apps. I have no idea if it works though.
