### ISSUE TITLE
Delete expired tokens from database

### ISSUE THREAD

**Issue by shvechikov** [evonove/django-oauth-toolkit#148]
I don't see any purging mechanism for expired tokens.
I think it's worth to have a management command to delete expired tokens.
Am I missing something here?

**Comment by alewisohn** [comment]
I came up with the following logic for cleaning up tokens. In our app, it runs as a periodic task, but it could easily be converted to a management command.

```python
AccessToken.objects.filter(refresh_token__isnull=True, expires__lt=datetime.now()).delete()
```

Basically, we can delete any access tokens that have expired and that do not have a corresponding refresh token, i.e., the refresh token for that access token has been used. Unused refresh tokens and their related access tokens will still hang around. 

Without and expiration on refresh tokens, there's no way to clean them up without invalidating the related access tokens. A management command could be written that accepts an explicit expiration time for refresh tokens though.

**Comment by trbs** [comment]
Why not (at least) configure a static REFRESH_TOKEN_EXPIRE_SECONDS which indicated how long we want to keep the access_token + refresh_token pair after the access_token has expired.

The cleanup mechanism could then be:
```
with transaction.atomic():
    if REFRESH_TOKEN_EXPIRE_SECONDS:
        refresh_expire_date = timezone.now()-timedelta(seconds=REFRESH_TOKEN_EXPIRE_SECONDS)
        RefreshToken.objects.filter(access_token__expires__lt=refresh_expire_date).delete()
    AccessToken.objects.filter(refresh_token__isnull=True, expires__lt=datetime.now()).delete()
```

Futher steps might be to be able to override the REFRESH_TOKEN_EXPIRE_SECONDS per application. So that one might have unlimited refresh_tokens on some applications (ios/android apps?) and not on others (web api's).

**Comment by SilviyaRepo** [comment]
Could you tell me elaborately ow you achieved this???

**Comment by bforchhammer** [comment]
We use the oauth toolkit with a quite a large user-base and are getting to a point where the access tokens table is getting quite large; we have >100M tokens with only a small percentage active. I would love to see a way to purge expired ones, without having to delete any refresh tokens.

The cleanup script above (and in the related issue/pull request) looks good, but it only deletes access tokens for which the refresh token has been used already. Could we instead make the relationship between access and refresh token optional and delete *all* expired access tokens?

**Comment by synasius** [comment]
Closed by #249

**Comment by silviyaranirepo** [comment]
Happy to see .. Could I use REFRESH_TOKEN_EXPIRE_SECONDS in OAUTH2_PROVIDER ? :+1:

**Comment by synasius** [comment]
Yes, it's possible now that #249 is merged. Just wait till the next DOT release. 

Or if you can't wait install the development version:
```
pip install https://github.com/evonove/django-oauth-toolkit/archive/master.zip
```

**Comment by shvechikov** [comment]
Thank you!
