### ISSUE TITLE
Allow to configure the Server class

### ISSUE THREAD

**Issue by thedrow** [evonove/django-oauth-toolkit#150]
We define multiple custom grants and it's really annoying that I have to override the view and copy/paste django-oauth-toolkit's urls.py instead of including.

**Comment by outsbart** [comment]
Hi @thedrow, thanks for reporting this issue.

This has been solved with [Pull Request 299](https://github.com/evonove/django-oauth-toolkit/pull/299). You can now provide the server class trough the OAUTH2_SERVER_CLASS setting.
