### ISSUE TITLE
Override authorization approval decision

### ISSUE THREAD

**Issue by DavidMuller** [evonove/django-oauth-toolkit#156]
I'd like to add a flag that allows a user to skip the authorization ("I authorize foobar_app to access my_app") process completely.  Although this might be a rare use case, as per the spec (4.1.1):

> 10.2.  Client Impersonation 
...
If the request is valid, the authorization server authenticates the resource owner and obtains an
authorization decision (by asking the resource owner or by establishing approval via other means).

My imagined use case is for handling trusted in-house applications--it would be nice skip the confirmation screen even when this is the first time use of the application and there was no previous authorization.  This would fall under obtaining an authorization decision via "other means."

**Comment by masci** [comment]
Resolved
