### ISSUE TITLE
Auto increment id for accesstoken table is not sufficient for large applications

### ISSUE THREAD

**Issue by oreh** [evonove/django-oauth-toolkit#177]
Currently, the PK of accesstoken table is using int type (as default django table id does). But this 32-bit field can only hold around 2 billions records. The keys will be used out in a year if you have 10 millions users who generate new keys on a daily basis. 

Can we change the type from int to bigint? Or even better, can we use 'token' as the PK?

**Comment by masci** [comment]
We're currently planning to support both django1.7 and south1.0 migrations, so we prefer to postpone the resolution of this issue after that.

**Comment by jleclanche** [comment]
I'd like to change all IDs to use BigAutoField but this requires Django 1.10 so we might not be able to do it for a while.
