### ISSUE TITLE
Single Access Tokens

### ISSUE THREAD

**Issue by abhillman** [evonove/django-oauth-toolkit#179]
Is there a great way to ensure that one user can only have one valid token at a time? An alternative is to use middleware to do something like:

    from oauth2_provider.models import AccessToken
    AccessToken.objects.exclude(
        id__in=[AccessToken.objects.filter(user=request.user).last().id]
    ).filter(user=request.user).update(expired=True)

**Comment by masci** [comment]
We don't enforce such behaviour in the library, so implementing your own middleware is the way to go.

**Comment by hckjck** [comment]
I wonder if there is really a use case to have multiple valid access tokens for given application + scope + resource owner. I imagine the current implementation could be abused to flood server with a huge amount of access tokens. IMHO this should be restricted, but please correct me if I missed something.
