### ISSUE TITLE
Is there a way to generate a token for a user programmatically?

### ISSUE THREAD

**Issue by thisiscam** [evonove/django-oauth-toolkit#181]
Hi I'm using this beautiful library to build an app. What I'm trying to do is to render back a response with access_token when a user first register. Is there a way to generate an access_token for a user programmatically? I dig through the library but it seems that we are heavily relying on oauthlib and there isn't an apparent way to add a token for an authenticated user?

**Comment by masci** [comment]
Sorry, the workflow you're trying to implement is way different from any OAuth2 flow I'm aware of and it is not supported neither by oauthlib nor by DOT.
