### ISSUE TITLE
Browser Clients

### ISSUE THREAD

**Issue by glassresistor** [evonove/django-oauth-toolkit#189]
Is there an endpoint for clients without a secret?  Since our client is in the browser there isn't a good way to really protect the clients id or secret and having to do basic authentication seems not helpful without that.
Any advice on the best practices for working with browser clients?

**Comment by forty4487** [comment]
building an angularjs app as well and came across the same issue.  migrating to django-oauth-toolkit from django-oauth2-provider for a django 1.7 upgrade.  would think changing the application type from confidential to public would mean it would only require the client_id, but no dice.

**Comment by glassresistor** [comment]
Yeah I'm doing the same thing.  If anyone figures out a way to do this right please let me know.

**Comment by btnz** [comment]
I have some endpoints that just use SessionAuthentication as the auth classes (as they're accessed via browser only and not phone app, but no reason why they couldn't use both), but I'm in a situation where the users need to be logged in to be access the pages that hit these endpoints anyway.  I've only  just done it recently, but seems to work OK so far.  Possibly not at all what you're talking about though.

**Comment by dustinfarris** [comment]
Remember that Application.client_secret [is optional](https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L70-L71).  I use django-oauth-toolkit with Ember.js and do not provide a secret key during the exchange.

**Comment by glassresistor** [comment]
Is there a place that describes that well?  I haven't been able to parse
the docs as well as I would like.

On Tue, Feb 3, 2015 at 12:30 PM, Dustin Farris <notifications@github.com>
wrote:

> Remember that Application.client_secret is optional
> <https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L70-L71>.
> I use django-oauth-toolkit with Ember.js and do not provide a secret key
> during the exchange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evonove/django-oauth-toolkit/issues/189#issuecomment-72728182>
> .
>



-- 
Mikela

**Comment by dustinfarris** [comment]
Not that I'm aware of.  I struggled with the secret token thing too for a while before realizing it wasn't required.

**Comment by glassresistor** [comment]
How did you config the application?

On Tue, Feb 3, 2015 at 12:47 PM, Dustin Farris <notifications@github.com>
wrote:

> Not that I'm aware of. I struggled with the secret token thing too for a
> while before realizing it wasn't required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evonove/django-oauth-toolkit/issues/189#issuecomment-72731273>
> .
>



-- 
Mikela

**Comment by palazzem** [comment]
I'm the maintainer of an AngularJS application served as a static page with ``nginx``. The backend
application uses DOT (0.7.2) and DRF (2.4.x).

All REST endpoints are protected with OAuth2, making one exception that uses a session authentication (ex: using the ``LoginRequiredMixin`` available through ``braces`` package). In this endpoint we call a custom ``AuthorizationView`` that returns an access token for a specific ``cliend_id``, defined in our Django settings.

Besides that, we provide the ``AuthorizationView`` default behavior through another endpoint. About the OAuth2 application, we're using an *Implicit grant type* with a *Confidential client type*.

This is an example of the returned token when you make an authenticated call through your browser / Javascript application:

```
{"scope": "read+write", "expires_in": "3600", "access_token": "123456", "token_type": "Bearer"}
```

Whenever the Angular application makes the first call to our service, it asks for a valid token that will be used in all future calls. This process is repeated every time the token expires.

If you're going to use this flow, the token endpoint could be improved using the built-in Django cache.
Furthermore, if you're using AngularJS, you could implement an ``Interceptor`` that catches all 401 errors and that automatically retrieves tokens on its own when they are expired, while appending
bearer tokens to all requests headers. This will make OAuth2 authorization transparent to your application.

Hope it helps!
Cheers.

**Comment by palazzem** [comment]
I’m closing this issue because it has been inactive for a few months.
Don't worry to reopen this issue if you encounter any related problems, or if you want to further discuss your implementation with the DOT community.

Thank you!
