### ISSUE TITLE
Any reason for allowing name to be empty?

### ISSUE THREAD

**Issue by drager** [evonove/django-oauth-toolkit#193]
Hi!

I wonder why the name field accepts to be empty? Same goes for client_secret.

https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L72

Personally when using this and allowing external users to register applications I do want their applications to have name.

**Comment by poswald** [comment]
The `client_secret` is allowed to be an empty string in some of the grant types. The name isn't strictly necessary either. I'd suggest creating your own views/forms rather than using the ones packaged into the app to add your own validations.
