### ISSUE TITLE
Return user along with token

### ISSUE THREAD

**Issue by maryokhin** [evonove/django-oauth-toolkit#194]
Hello, I am using DOT with DRF and have a standard `/auth/token/` password grant endpoint for clients of my REST API. When clients authenticate they don't know what user they are representing, all they get is an auth token. Because of this, I need to support an additional endpoint `/users/self/` for actually getting the user. 

I also noticed that DOT doesn't use DRF serializers but just dumps json from the views. So, to support my use-case should I override the view myself? And what is a general guidance for these kind of things with OAuth?

**Comment by clintonb** [comment]
OAuth2 is not a user API. The token endpoint should only return access tokens. Once you have an access token you should query your user API (that you create) for user information. You might also investigate OpenID Connect which is built atop OAuth2 and uses claims/scopes to get user info along with the access token.

As for DOT not using DRF serializers, that makes sense. The relatively light amount of information being processed by OAuth2 doesn't really warrant an entire REST framework.
