### ISSUE TITLE
Default granted scopes

### ISSUE THREAD

**Issue by gonification** [evonove/django-oauth-toolkit#195]
Currently, if a request for a token is sent that lacks a 'scope' parameter the token is given all of the available scopes.

Is this expected behavior or should the token be provided with no scopes? I am inclined to believe the latter is appropriate.

**Comment by synasius** [comment]
Yes it is expected.
Please read http://tools.ietf.org/html/rfc6749#section-3.3

**Comment by synasius** [comment]
@gonification 
a few more infos
a token should always have scopes. We should add support to define the default list of scopes returned when `scopes` parameter is missing from the authorization request. See #16

**Comment by outsbart** [comment]
Since #333 we no longer need to keep this issue open.
