### ISSUE TITLE
auto generated admin listing pages don't provide much info

### ISSUE THREAD

**Issue by honestbleeps** [evonove/django-oauth-toolkit#205]
I was thinking of submitting a PR to improve the utility of the admin, but it seems there's some intentional obfuscation going on with your own custom class (RawIDAdmin) - so perhaps I'm overlooking something.

I've made overrides in my own django app so that I can actually list out the fields on the listing page and would be happy to submit a quick PR, but I am wondering if there's a specific reason that the admin listing page just lists tokens and nothing else?

Thanks!

**Comment by jleclanche** [comment]
I landed some fixes which improve the functionality of the admin pages a while back, they'll be in the next release!
