### ISSUE TITLE
feature request: application specific scope restrictions

### ISSUE THREAD

**Issue by honestbleeps** [evonove/django-oauth-toolkit#216]
I've been working on this myself, as it's a need for a project I'm working on, but here is a formal issue for discussion of the ideal implementation (mine is a bit hacked together), etc.

**What is the request**:

django-oauth-toolkit offers the ability to create custom scopes, but does not have a way to restrict each application to a separate subset of scopes.

the need may arise (as it has in my case) to not give all applications access to all scopes - some scopes may be restricted to more trusted applications/individuals.  For example, you may want to grant all applications a "read_basic_details" scope, but only trusted applications should be able to use the "read_full_details" scope.

**Suggested course of action**:

My implementation adds an allowed_scopes field to the application model.  Just like in the OAuth spec, the scopes are listed as space-separated strings.  When an access token is requested, the user is only given the option to request the scopes present in allowed_scopes -- this allows any application to be restricted only to specific scopes.

My pull request, to my own fork, is here:

https://github.com/honestbleeps/django-oauth-toolkit/pull/1

**TODO**:
- My code is probably suboptimal, and should be reviewed and perhaps redone.
- It stands to reason that if the site owner wants to restrict scopes, then application owners should not be able to edit the allowed_scopes field. I've not implemented this, as I'm just using waffle tags to only allow site administrators access to create or view the listing of applications for now. Ideally, to keep django-oauth-toolkit as an all in one / turnkey solution, this problem might be best addressed within the package itself.

Thanks for your consideration and review!

**Comment by masci** [comment]
Also see #130

**Comment by honestbleeps** [comment]
I just wanted to check in and see if any of the project owners have had a chance to take a look at my implementation. I'd love to see this (or something like it) merged, and I'd be happy to refine based on any feedback you may have.  Thanks!

**Comment by cleder** [comment]
:+1: This is over one year old now. For me it is a valid use case (and one I am having). What are the maintainers thoughts about this? @honestbleeps Your code looks fine to me ;-)

**Comment by JensTimmerman** [comment]
@honestbleeps pull request was made against his own repo, I rebased it on master and removed a setting and made it against this repository, in #395

**Comment by itemir** [comment]
+1 for this. Would love to this merged.

**Comment by poswald** [comment]
It sounds like people think that #395 should be merged instead of this one... but that one is not passing tests yet. If you want this, I suggest looking into helping that one along.

**Comment by victorct** [comment]
@JensTimmerman Any update on this issue?

**Comment by jleclanche** [comment]
Customizable scope backends were landed in 0.12... Im closing this as done.
