### ISSUE TITLE
0.7.2 to 0.8.0

### ISSUE THREAD

**Issue by jairhenrique** [evonove/django-oauth-toolkit#219]
The `skip_authorization` field from `AbstractApplication` is not present on migrations. When I upgrade `django-oauth-toolkit`, I receive this error when try to get token.

```
OperationalError at /oauth/token/
(1054, "Unknown column 'oauth2_provider_application.skip_authorization' in 'field list'")
```

**Comment by synasius** [comment]
That is correct since Application is a swappable model and you should keep those migrations in your app

**Comment by dustinfarris** [comment]
That doesn't make sense.  Why are there migrations at all then?

**Comment by jairhenrique** [comment]
@dustifarris :+1:

**Comment by synasius** [comment]
Ok, I changed my mind on that
the migration has been added here 62847af5c322e74075ff454fffcd824a2ebb2b57
