### ISSUE TITLE
refresh_token doesn’t revoke the related access_token in database

### ISSUE THREAD

**Issue by H0neyBadger** [evonove/django-oauth-toolkit#220]
The old access_token is still usable when I refresh a non-expired token
Is it a bug? 

The original token :
```json
    {
        "token_type": "Bearer",
        "expires_in": 36000,
        "access_token": "vr89rkJnM9aHlTssE604Eq1qfRCQSO",
        "refresh_token": "rxx50tQhhYMK7izxEa98sSRxb6Nkts",
        "scope": "read write"
    }
```
Then, I call /o/token/  with the following request
```python
post_data = {
            'grant_type':'refresh_token',
            'client_id':'my_client_id',
            'client_secret':'s3krit', 
            'refresh_token':'rxx50tQhhYMK7izxEa98sSRxb6Nkts'
        }
```

The json response (status 200 OK)
```json
{
    "expires_in": 36000,
    "scope": "read write",
    "refresh_token": "rUlsE6hPVY16ftpgHryBSPt5S9BBoK",
    "access_token": "MyQoMAfEeWB21I5F0f1vJumqrJMpVU",
    "token_type": "Bearer"
}
```
When I go back to the DOT database, I see the following objects:
```json
    {
        "token_type": "Bearer",
        "expires_in": 33569,
        "access_token": "vr89rkJnM9aHlTssE604Eq1qfRCQSO",
        "refresh_token": null,
        "scope": "read write"
    },
    {
        "token_type": "Bearer",
        "expires_in": 35984,
        "access_token": "MyQoMAfEeWB21I5F0f1vJumqrJMpVU",
        "refresh_token": "rUlsE6hPVY16ftpgHryBSPt5S9BBoK",
        "scope": "read write"
    }
```
The first access_token is orphan but it's still usable until the expiration date is reached

**Comment by masci** [comment]
According to the [RFC](https://tools.ietf.org/html/rfc6749#section-1.5):

> Refresh tokens are issued to the client by the authorization server and are
> used to obtain a new access token when the current access token
> becomes invalid or expires, or to obtain additional access tokens
> with identical or narrower scope (access tokens may have a shorter
> lifetime and fewer permissions than authorized by the resource
> owner).

So I would say the current behaviour is correct. That said, the standard specs seem to be open to interpretation on this matter, or at least do not specify explicitly whether a token should be kept or evicted upon refreshing, so maybe we could let users configure DOT behaviour, not sure at the moment how much effort it's needed.

**Comment by H0neyBadger** [comment]
It make sense.
I really enjoy this kind of answer.
Thanks a lot @masci !
