### ISSUE TITLE
Incorrect documentation of models.AccessToken.expires

### ISSUE THREAD

**Issue by ze-phyr-us** [evonove/django-oauth-toolkit#225]
The [AccessToken model docs](https://django-oauth-toolkit.readthedocs.org/en/latest/models.html#oauth2_provider.models.AccessToken) say:

> expires: Expire time in seconds, defaults to settings.ACCESS_TOKEN_EXPIRE_SECONDS

However, the actual model defines this as a datetime field (`expires = models.DateTimeField()`) and there is no default.

This was just a little confusing when I tried to create an `AccessToken` instance manually for API unit tests.

**Comment by synasius** [comment]
Yes, docs should be changed
Thnx
