### ISSUE TITLE
Creating a token without username/password for single user? (Signed up/in with Python Social Auth)

### ISSUE THREAD

**Issue by felix-d** [evonove/django-oauth-toolkit#226]
I'm using Python Social Auth and Django OAuth Toolkit to manage my user accounts and restrict access to my REST API.

I can create a token for users that sign up manually with my app by using the regular

```curl -X POST -d "grant_type=password&username=<user_name>&password=<password>" -u"<client_id>:<client_secret>" http://localhost:8000/o/token/```

But when I register my users with PSA by their access token, I'd like to create a OAuth2 Toolkit token for my own app and return it as JSON to the client so it can use it for making requests with my API.

For now, what I am doing is reusing the same token as the one returned my the third party provider.

```
@psa('social:complete')
def register_by_access_token(request, backend):
    # This view expects an access_token GET parameter, if it's needed,
    # request.backend and request.strategy will be loaded with the current
    # backend and strategy.
    token = request.GET.get('access_token')
    user = request.backend.do_auth(token)
    if user:
        login(request, user)
        app = Application.objects.get(name="myapp")
        AccessToken.objects.get_or_create(user=user,
                                          application=app,
                                          expires=now() + timedelta(days=365),
                                          token=token)
        return "OK" # I will eventually return JSON with the token
    else:
        return "ERROR"
```
Is there another way?

**Comment by yarbelk** [comment]
+1 - except using allauth + rest_auth

**Comment by victorgutemberg** [comment]
I found one solution to this problem, but I'm using Django Rest Framework as well. https://pypi.python.org/pypi/django-rest-framework-social-oauth2

But, I think it may be helpful if you have a look on their code. 

Cheers.

**Comment by victorgutemberg** [comment]
Have a look in the view convert_token:
https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/blob/master/rest_framework_social_oauth2/views.py

It aims to convert a third part token to a token for your app, I think you answer is here.

**Comment by felix-d** [comment]
I've written an article about the issue 
http://httplambda.com/a-rest-api-with-django-and-oauthw-authentication/

and created a repo with the related code
https://github.com/felix-d/Django-Oauth-Toolkit-Python-Social-Auth-Integration

**Comment by jyr** [comment]
Hi @felix-d 

Do you have an article backup? I try make a similar solution.

**Comment by Sticky-Bits** [comment]
Hi @jyr, we just faced this problem too, felix's article link now leads to spam sites, but the relevant part of his solution is in his github here: https://github.com/felix-d/Django-Oauth-Toolkit-Python-Social-Auth-Integration/blob/master/users/tools.py

**Comment by Zorig** [comment]
@Sticky-Bits i am having same problem too, but could not figure out how to integrate with python social auth, Do i have to pass `social:complete<backend>` response to this `register_by_access_token` view?

**Comment by Sticky-Bits** [comment]
@Zorig No idea sorry, we don't use python social auth. We just needed to make an OAuth token without using a username/password. Ended up using similar code from the link above.
