### ISSUE TITLE
Add docs: how to use migrations on dango>1.7 with a custom application

### ISSUE THREAD

**Issue by synasius** [evonove/django-oauth-toolkit#227]
When using a custom application model migrations don't work out of the box.
The `makemigrations` command should fail with an error like:

```
ValueError: Lookup failed for model referenced by field oauth2_provider.Grant.application: foo.MyApp 
```

Let's say you have your custom user model in `foo.MyApp`, follow these steps to correctly create migrations for your app:
1. Check you **DON'T** have `OAUTH2_PROVIDER_APPLICATION_MODEL` in your settings or it is commented out.
2. Check both `oauth2_provider` and `foo` are listed in `INSTALLED_APPS`.
3. Run `makemigrations` command
4. Now add or uncomment `OAUTH2_PROVIDER_APPLICATION_MODEL`\
5. Run `migrate` command.

**Comment by dustinfarris** [comment]
Is this for someone who is a first-time user, or someone upgrading from Django < 1.7, or someone upgrading from DOT < 0.8?

**Comment by synasius** [comment]
You can reproduce the error with django>=1.7 and the current DOT master branch.

Create a new project, add an app with the custom application model and set the OAUTH2_PROVIDER_APPLICATION_MODEL in the settings.
Then try to run makemigrations and you'll get the error.

The steps above are the only workaround I'm aware of.

**Comment by femesq** [comment]
@synasius Is the equivalent process necessary for those still using Django 1.6+South, or this issue is Django Migration (>1.7) issue?

**Comment by synasius** [comment]
the issue occurs on a new Django>=1.7 project when using a custom application model.

Please note that changing the Application Model has the same effect of changing user model, so the same warnings applies. Please read https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#substituting-a-custom-user-model carefully!!

**Comment by mitchellrj** [comment]
It may be useful for people adding Django-OAuth-Toolkit to an existing project to be aware of `run_before`:

https://docs.djangoproject.com/en/1.9/howto/writing-migrations/#controlling-the-order-of-migrations

Any migration that adds a swappable application model should have:

    run_before = [
        ('oauth2_provider', '0001_initial'),
    ]

specified in it.

**Comment by jleclanche** [comment]
Closing this as 1.11 is the minimum version supported and it's been too long.
