### ISSUE TITLE
Package authentication does not pass in request

### ISSUE THREAD

**Issue by glynjackson** [evonove/django-oauth-toolkit#230]
I have a custom ``authentication`` backend which I use alongside django-oauth-toolkit at ``token/``. But,  I need to have access to the request object, however because you don't pass it in here:

https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L344

I cannot access it in my own authentication. Currently I have to do some nasty stuff or add it manually to the package where it calls  ``u = authenticate(username=username, password=password, request=request)``.

Would it be possible to pass in the request object during your own authenticate so that we can have access to it in our own  authentication systems? :) I can create a pull request for this but need to know if this is sensible ok etc. Thanks

**Comment by synasius** [comment]
Hi @glynjackson 

sorry but this can't be added to DOT. Instead you should customize your validator class to suit your needs and it is really easy to do, just create a custom validator which extends `oauth2_provider.OAuth2Validator` and override the methods you need. 

```
class MyValidator(OAuth2Validator):
    def validate_user(self, username, password, client, request, *args, **kwargs):
        u = authenticate(username=username, password=password, request=request)
        ...
```

Then you add the following parameter to your settings to tell DOT to use your own validator class.

```
OAUTH2_PROVIDER = {
    'OAUTH2_VALIDATOR_CLASS': 'yourapp.yourmodule.MyValidator'
}
```

and it works!

**Comment by glynjackson** [comment]
@synasius That makes sense! Thank you:)
