### ISSUE TITLE
Custom (template for) AuthorizationView

### ISSUE THREAD

**Issue by stefankoegl** [evonove/django-oauth-toolkit#241]
I'd like to either implement my own `AuthorizationView` or at least use a custom template for it. If I'd subclass either `AuthorizationView` or `BaseAuthorizationView`, how would I get django-oauth-toolkit to use my custom class?

I couldn't find any answer to this in the docs, but I'll gladly update them if somebody can point me in the right direction.

**Comment by honestbleeps** [comment]
I've done exactly this with other views...

in my main urls.py, I performed an override, like so:

    # django-oauth-toolkit overrides
    url(r'^o/applications/register/$',
        login_required(revalidate_password(5 * 60)(OAuthRegistrationFormView.as_view(
            form_class=OAuthRegistrationForm))), name="register"),
    url(r'^o/applications/(?P<pk>\d+)/update/$',
        login_required(revalidate_password(5 * 60)(OAuthUpdateFormView.as_view(
            form_class=OAuthRegistrationForm))), name="update"),
    url(r'^o/applications/(?P<pk>\d+)/$',
        login_required(revalidate_password(5 * 60)(ApplicationDetail.as_view())), name="detail"),

    # django-oauth-toolkit standard views
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

**Comment by outsbart** [comment]
@honestbleeps is right, that's the suggested way.
