### ISSUE TITLE
revoke token without client_secret for public applications and password grant_type

### ISSUE THREAD

**Issue by flc** [evonove/django-oauth-toolkit#242]
Let's assume I have an application with the following parameters:
client_id: foo
client_secret: -
client_type: public
authorization grant type: resource owner password based

Yes, the client_secret is empty/not specified.

I can successfully get an access token and refresh token (without specifying client_secret) which is nice because I think the spec allows this (note that the app is public and the grant_type is password).
What I can't do however is to revoke the token. And it's because the app does not have a client_secret.
I get a 401 UNAUTHORIZED `{"error": "invalid_client"}` error response.

Of course I can easily overcome this issue by giving a client_secret to the application and everything works but I think it would be good to support the no client_secret case as well and keep things consistent.

When acquiring a token this logic applies when validating the client:
https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py#L98

At revocation this logic applies:
https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/endpoints/revocation.py#L123

And the DOT's validator class does not allow the client_secret to be empty in this case.
https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L156

I also understand that while token creation is implemented in a grant type specific class (ResourceOwnerPasswordCredentialsGrant) token revocation doesn't depend on the grant type and is implemented in a more generic way in the RevocationEndpoint class.

Although I'm not entirely sure whether the implementation of oauthlib or django-ouath-toolkit should be refined. Or I just simply don't get something. :)

What do you think?

**Comment by synasius** [comment]
Solved in #247
