### ISSUE TITLE
How to customize token expiration time?

### ISSUE THREAD

**Issue by gauravdott** [evonove/django-oauth-toolkit#243]
I have tried importing oauth2 settings in my settings file as follows:

```python
from oauth2_provider.settings import oauth2_settings
oauth2_settings.AUTHORIZATION_CODE_EXPIRE_SECONDS = 'custom value here'
```

But it doesn't work and oauth2_provider is issuing tokens with default time (36000) only. 

Any help is appreciated.

**Comment by maryokhin** [comment]
Worked for us by putting this in our Django settings:
```python
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 600,
}
```

**Comment by masci** [comment]
@gauravdott that provided by @maryokhin is the right way to specify DOT settings, see https://django-oauth-toolkit.readthedocs.org/en/latest/settings.html

**Comment by riyajk** [comment]
How we can set it dynamically? Is it possible to set it different for different api?

**Comment by RAJKRIS** [comment]
> How we can set it dynamically? Is it possible to set it different for different api?

Do we have a provision for this?

**Comment by Lalee10** [comment]
@RAJKRIS @riyajk I don't know if its the correct way or not but I was able to achieve this by extending the class [OAuth2Validator](https://github.com/jazzband/django-oauth-toolkit/blob/2f3dd4539b37f88f2380258fff21b76837766979/oauth2_provider/oauth2_validators.py#L67) and overriding the [save_bearer_token](https://github.com/jazzband/django-oauth-toolkit/blob/2f3dd4539b37f88f2380258fff21b76837766979/oauth2_provider/oauth2_validators.py#L534)

```py
# My custom validator class
class CustomOAuth2Validator(OAuth2Validator):
  def save_bearer_token(self, token, request, *args, **kwargs):
    expires_in = 30 # or perform custom logic to calculate the expiry time
    token['expires_in'] = expires_in
    super().save_bearer_token(token, request, *args, **kwargs)
```

And providing my custom class to OAUTH2_PROVIDER settings
```py
# settings.py
OAUTH2_PROVIDER = {
  "OAUTH2_VALIDATOR_CLASS": "myapp.oauth2.CustomOAuth2Validator"
}
```
