### ISSUE TITLE
No installed app with label 'oauth2_provider'.

### ISSUE THREAD

**Issue by raphaeltorres** [evonove/django-oauth-toolkit#256]
I'm having an error like this.

LookupError at /o/applications/
No installed app with label 'oauth2_provider'.
Request Method:	GET
Django Version:	1.7.5
Exception Type:	LookupError
Exception Value:	
No installed app with label 'oauth2_provider'.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/apps/registry.py in get_app_config,

**Comment by raphaeltorres** [comment]
already solve the issue.

**Comment by zmunk** [comment]
How did you solve the issue?
