### ISSUE TITLE
Python 2.6 'No module named urllib.parse'

### ISSUE THREAD

**Issue by Pkthunder** [evonove/django-oauth-toolkit#258]
I am attempting to run 'python manage.py syncdb' (I am following your installation tutorial), but I keep getting the error above. I know the error means I am trying to run python 3 code with python 2, but I don't understand why this is happening.

Python 2.6.6
Django 1.5.4
six 1.4.1
pip 7.0.3

I also tried:
$ python
$ >>> import six
$ >>> six.PY2
True
$ >>>six.PY3
False

I get the following error message after installation (pip install django-oauth-toolkit)

(oauth_pyenv)$ Validating models...

Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x1bc9dd0>>
........
  File "/home/.../oauth_pyenv/lib/python2.6/site-packages/oauth2_provider/models.py", line 14, in <module>
    from .validators import validate_uris
  File "/home/..../oauth_pyenv/lib/python2.6/site-packages/oauth2_provider/validators.py", line 8, in <module>
    from django.utils.six.moves.urllib.parse import urlsplit, urlunsplit
ImportError: No module named urllib.parse

**Comment by outsbart** [comment]
I'm closing this issue since we've dropped Python 2.6 support
