### ISSUE TITLE
How to implement Multi-Device login

### ISSUE THREAD

**Issue by tspecht** [evonove/django-oauth-toolkit#259]
Hey,

I am currently trying out django-oauth-toolkit to implement a multi-device OAuth2 login for my Django-based REST API. I played around with it a little and already got the basic setup running. However, when it comes to using refresh tokens in order to get a fresh access token, I am running into some issues with create_token_response which seems to delete all other RefreshToken objects.

> Device A logs in, receives AccessTokenA and RefreshTokenA. Device B logs in, received AccessTokenB and RefreshTokenB. 
> Now the AccessTokenA expires. Device A uses its RefreshTokenA to get a new RefreshToken. The create_token_response function creates a new AccessTokenA1 and RefreshTokenA1 and returns it. 
> While executing the function, all other refresh tokens seem to be deleted. Thus, the RefreshTokenB of Device B is deleted. When now the access token AccessTokenB of Device B expires, Device B tries to use the still locally stored RefreshTokenB to get a new access token but instead receives an error because RefreshTokenB was already deleted from the database.

Is this correct and if yes, are there any ways to circumvent this?

**Comment by jleclanche** [comment]
Closing old unanswered questions. Reopen if its still a problem.
