### ISSUE TITLE
Django 1.4 doesn't support

### ISSUE THREAD

**Issue by nuklea** [evonove/django-oauth-toolkit#263]
Because `resolve_url` shortcut doesn't exist in 1.4. Support broked in https://github.com/brack3t/django-braces/commit/0331b927228ddf532ea59e36d48bf4da057c6930.

**Comment by outsbart** [comment]
Hi @nuklea, thanks for reporting this issue.

As you can see in #322 we are dropping support for Django 1.4. 
So we are not going to investigate on this issue.

Cheers
