### ISSUE TITLE
Django REST Framework - Browseable API 

### ISSUE THREAD

**Issue by 0x8DEADF00D** [evonove/django-oauth-toolkit#265]
According to [this question on stackoverflow](http://stackoverflow.com/questions/24387009/django-restframework-browsable-api-login-with-ouath) it should be possible to use the browseable API from the Django REST Framework package.

However, declaring the `SessionAuthentication` authentication class didn't work, I get an error that I'm lacking permission:

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 
        'oauth2_provider.ext.rest_framework.OAuth2Authentication', 
        'rest_framework.authentication.SessionAuthentication', 
    ), 
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'PAGE_SIZE': 10,
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}
```

These are my scopes:

```
OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
        'foods': 'Access to Foods'
    }
}
```

and this is my view that cannot be accessed through the browseable API if the `TokenHasScope` permission class has been set:

```
class FoodGroupViewSet(ViewSetBase):
    permission_classes = [IsAuthenticated, TokenHasScope]
    required_scopes = ['foods']
    queryset = FoodGroup.objects.all()
    serializer_class = FoodGroupSerializer`
```

Is this a bug or am I doing anything wrong here?

**Comment by marteinn** [comment]
I am experiencing the same issue. 

Django==1.8.5
djangorestframework==3.3.0
django-oauth-toolkit==0.9.0

**Comment by synasius** [comment]
`TokenHasScope` permission fails because there is no token when you authenticate with `SessionAuthentication`. The permission class does not take into account if you are authenticating with the session or with an access_token and I think it's  a sane default.

If you want to avoid the check when authenticating with a non OAuth2 backend you can use this permission class:
``` python
from oauth2_provider.ext.rest_framework import OAuth2Authentication, TokenHasScope

class WeakTokenHasSope(TokenHasScope):
    def has_permission(self, request, view):
        if request.successful_authenticator != OAuth2Authentication:
            return True
        return super().has_permission(request, view)
```

**Comment by justinanderson** [comment]
@synasius Shouldn't that be `if not isinstance(request.successful_authenticator, OAuth2Authentication)`?

**Comment by JensTimmerman** [comment]
We ( actually @werthen ) used a similar aproach to create an IsAuthenticatedOrTokenHasScope permission, see #396
