### ISSUE TITLE
Custom Application admin registration

### ISSUE THREAD

**Issue by Kmaschta** [evonove/django-oauth-toolkit#267]
Hello,

I'm improving my Application model with a lot of fields (especially a list of users) thanks to this setting `OAUTH2_PROVIDER_APPLICATION_MODEL`.

But the model becomes difficult to manipulate and I need to change its registration on django admin.

I see that you use `RawIDAdmin` class (here https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/admin.py), but how can I change it ?

Thanks in advance

**Comment by jleclanche** [comment]
You can subclass the admin in question and re-register it!

**Comment by evanxg852000** [comment]
Hi in my case In facing a circular dependency, when I try to register the admin, it says it's already registered. But I also don't want to put it at the top of my installed apps
