### ISSUE TITLE
Extend Application Model - Display the extended fields in the forms.py

### ISSUE THREAD

**Issue by helixaros** [evonove/django-oauth-toolkit#269]
I would like when setting up an application (/o/application/) to have a foreign field added on another model I created in my application. This field I would like this to be displayed when registering an app.

I have created a model similar to this
from django.db import models
from oauth2_provider.models import AbstractApplication

class MyApplication(AbstractApplication):
    agree = models.BooleanField()

and added on my settings OAUTH2_PROVIDER_APPLICATION_MODEL='your_app_name.MyApplication'

however the problem is that even thought the additional field is added on the Database (when migrating the app), it does not get added on the Form when registering an application. 
Also for some reason when register an app after performing the above changes, I get page not found (when clicking the submit button in o/applications/) 

Can i get some help on that? I am sure its an easy explanation that I havent properly understood

**Comment by poswald** [comment]
I think if you have defined a custom model, then you would also have to create a custom form/view and use those instead of the built-in forms. You can probably do that by extending `ApplicationRegistration` and overriding `get_form_class`.
