### ISSUE TITLE
BUG: Application registration form not working for extended application models

### ISSUE THREAD

**Issue by mark-tan** [evonove/django-oauth-toolkit#274]
Submitting the registration form redirects to a 404 page when using a custom application model.

Upon initial inspection of the code, the problem seems to have been introduced in commit f5a1a493b939447076cb7af7553522b398b1d1eb while fixing #151. It looks like the form is using the default application model.

**Comment by jannon** [comment]
I just ran into this, too after upgrading to 0.9.0.  I'm not sure what issue really caused #151, but I'm running Django 1.7.10 and when I change the `RegistrationForm` code to 
```python
...
from .models import get_application_model

Application = get_application_model()

...

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ('name', 'client_id', 'client_secret', 'client_type', 'authorization_grant_type', 'redirect_uris')
```

everything works just fine.  So +1 to changing `RegistrationForm` back to properly using custom application models

**Comment by detectedstealth** [comment]
Any status on this I have just ran into the same situation tonight. Will the pull request that @jannon made make it into master soonish or do I have to hack my local version? On a deadline need to use a custom model. 

Using Django 1.8.4
