### ISSUE TITLE
DRF Implicit grant type

### ISSUE THREAD

**Issue by creynold** [evonove/django-oauth-toolkit#275]
I'm using django rest framework, and I've added an application with "implicit" grant type. Whenever I POST to /o/token/ with the client_id, grant_type=implicit, username and password I get back "Error: unsupported_grant_type".

Using "password" grant type works fine. Anything I'm missing?

**Comment by leonid-s-usov** [comment]
You are missing some theory ;) https://tools.ietf.org/html/rfc6749#section-4.2

Implicit grant is implicit in a way that you don't specify it explicitly on the request. You set the response type to "token", client_id to a previously registered client (public client) and the redirect_uri to an URI registered with the client (a.k.a application). You don't specify username and password - the current Django user is taken and associated with the token being created. You are presented a View where you should click on Allow, and then the access token will be generated and added to the redirect_uri you specified.

**Comment by creynold** [comment]
I realized this a while back and forgot I had even made this post.. thanks for the reply though!
