### ISSUE TITLE
Requirements.txt shouldn't include oauthlib with ">="

### ISSUE THREAD

**Issue by jeduden** [evonove/django-oauth-toolkit#281]
With the breaking release 1.0.0 of oauthlib django-oauth-tooklit automatically pulled an backward-incompatible version of oauthlib. 
I would suggest that django-oauth-toolkit fixes the version using ==  instead of using >= in https://github.com/evonove/django-oauth-toolkit/blob/master/requirements/base.txt#L3

**Comment by masci** [comment]
@jeduden you're right, I was taking time to see if we can release oauthlib 1.0.1 on pypi any soon (see https://github.com/idan/oauthlib/issues/367), so I could made just one release of DOT containing the compatibility fixes.
I'll wait until tomorrow, then I will bake a bugfix release for DOT containing just the pinned requirement for oauthlib, waiting the 1.0.1

**Comment by jeduden** [comment]
The oauthlib release 1.0.0 also introduced a breaking change for the common.Request class (compared to 0.7.2) with this commit:
( https://github.com/idan/oauthlib/commit/539558a02edbadb8d6ef690fb0beb2510a5eeb17 )

I believe the current oauth2_validators.py also still depends on the old common.Request class behavior in this line:
https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L58

Should I create a separate issue for this one ?

**Comment by masci** [comment]
Let's use #277 to track compatibility issues, I fixed the validator anyway. I've not pushed the code yet because I would break the build.

**Comment by jeduden** [comment]
Awesome. Thanks !

**Comment by masci** [comment]
fixed in #245
