### ISSUE TITLE
Can't migrate from 0.7 to 0.8.2  or 0.9 on existing installation

### ISSUE THREAD

**Issue by oliverroick** [evonove/django-oauth-toolkit#286]
I have an installation of DOT with a custom application model. When I try to migrate from my existing 0.7 installation to either 0.8 or 0.9 I get the following exception:

```
ValueError: Lookup failed for model referenced by field oauth2_provider.Grant.application: applications.Application
```

The instructions in #227 don't help, running step 3 returns:

```
No changes detected
```

Any help is much appreciated.

**Comment by poswald** [comment]
Can you please try with the latest version... there's been some changes to the migrations since. Please reopen if it is still an issue. Also, please include any information about if you have overridden the application model or not and if so, how your models are set up.
