### ISSUE TITLE
Implementing Custom Application Model 0.9.0

### ISSUE THREAD

**Issue by neokree** [evonove/django-oauth-toolkit#289]
Hi, I have noticed that There is an error for implements a new custom application model. 
Following the docs I got an error when making migrations:

```
Lookup failed for model referenced by field oauth2_provider.RefreshToken.application: application.Application
```

This happens because the library tries to refers the custom model, but at the time it is not migrated yet. 
However, if I make migrations before add the OAUTH2_PROVIDER_APPLICATION_MODEL setting, all seems to work fine, but it doesn't because with migrate the **oauth2_provider_application** table is not removed by the database, and the oauth2_provider_accesstokens table is referred to the old oauth2_provider_application, not the new custom application model. 

I have explained how to resolve this problem with 0.9.0 in this post: https://groups.google.com/d/msg/django-oauth-toolkit/a5qTWOctc2A/5X6zapo-NgAJ

But for the next release I think that is more useful find a way to update references when settings changed, or update the docs adding migrations calls.

**Comment by jleclanche** [comment]
Merging into #227
