### ISSUE TITLE
Is 0.9.0 compatible with oauthlib 0.7.2?

### ISSUE THREAD

**Issue by lzen** [evonove/django-oauth-toolkit#292]
Hi, I understand the reason to pin oauthlib version and I think it is right thing to do. While there's another library in my app requires oauthlib 0.7.2 to work (app breaks with 1.0.1), I'm just wondering whether django-oauth-toolkit 0.9.0 (and possibly a few future versions too) would still be compatible with oauthlib 0.7.2 or not. If not I might have to stick with 0.8.2 for now. Thank you!

**Comment by synasius** [comment]
Hi Liang,

sorry but DOT 0.9.0 is tied to the api exposed in oauthlib 1.0.1 and it
can't work properly with oauthlib 0.7.2.

2015-09-15 1:28 GMT+02:00 Liang Zheng <notifications@github.com>:

> Hi, I understand the reason to pin oauthlib version and I think it is
> right thing to do. While there's another library in my app requires
> oauthlib 0.7.2 to work (app breaks with 1.0.1), I'm just wondering whether
> django-oauth-toolkit 0.9.0 (and possibly a few future versions too) would
> still be compatible with oauthlib 0.7.2 or not. If not I might have to
> stick with 0.8.2 for now. Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evonove/django-oauth-toolkit/issues/292>.
>



-- 
Federico Frenguelli

**Comment by lzen** [comment]
Hi Federico,

Thanks for the quick reply! No problem, I'll stick with 0.8.2 for now and get the latest version of DOT when we can upgrade oauthlib. Thank you!
