### ISSUE TITLE
Why do we keep the old access_token when using refresh_token?

### ISSUE THREAD

**Issue by lzen** [evonove/django-oauth-toolkit#293]
Hi,

I noticed when we use refresh_token to get a new pair of tokens, the old refresh_token gets deleted (expected) but the old access_token is still in the table and still valid until it expires. Is there a particular reason why it is designed this way? Thank you!

**Comment by Psykopear** [comment]
This is compliant to the RFC 6749, https://tools.ietf.org/html/rfc6749#section-1.5

As stated there:

>Refresh tokens are issued to the client by the authorization server and are used to obtain a new access token when the current access token becomes invalid or expires, **or to obtain additional access tokens** with identical or narrower scope (access tokens may have a shorter lifetime and fewer permissions than authorized by the resource owner).

**Comment by poswald** [comment]
Closing this to clear out the issue. If you disagree with that interpretation of the spec, please feel free to re-open it.
