### ISSUE TITLE
Django 1.9, url from future has been dropped

### ISSUE THREAD

**Issue by DheerendraRathor** [evonove/django-oauth-toolkit#301]
Hi, Django 1.9 alpha version has been released recently and main version will be up by December. There are many things changed and they have dropped `url` from `future`. I think we need to drop support for Django 1.4

**Comment by synasius** [comment]
This has been fixed by #306

**Comment by leonid-s-usov** [comment]
django 1.9 is officially out, but the aforementioned fix is still on master only. What are the plans regarding new version of the toolkit?
