### ISSUE TITLE
Django TokenHasScope 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by edwinmore1** [evonove/django-oauth-toolkit#302]
I am building a REST API with DRF and DOT testing on my local server work perfectly but the production server always throws me 401 UNAUTHORIZED, I'm going crazy and I find what my problem is, someone could help me with my problem,

**Comment by edwinmore1** [comment]
Solve,

in the apache config add 

WSGIPassAuthorization On

**Comment by hrahmadi71** [comment]
I've faced exactly the same issue, but I'm using Nginx server instead of Apache server. Does anyone know how to config Nginx so it works properly?
