### ISSUE TITLE
Authentication between own apps: frequent question

### ISSUE THREAD

**Issue by pySilver** [evonove/django-oauth-toolkit#303]
Hi,

Thanks for great extension! It may sound more like SO question, but I'm a little bit confused with Application model. Reviewing issues here, I'm not the only one with this kind of problem.

So, what I have is:
- Django application, lets call it _application-backend_
- Clientside application, lets call it _angularjs-client_ (our own)
- 3rd party applications that needs access to resources of _application-backend_
- Users that needs API access to their account, so they can access their data programmatically

Thats kinda typical setup. However, it raises some obvious questions:
1. Application instance requres User to be attached. So, does _angularjs-client_ app instance should be created for every registered user? Guys from yeti [uses this approach](https://yeti.co/blog/oauth2-with-django-rest-framework/). Is it correct design and one should treat own apps like 3rd parties?
2. What about users that needs an API access to their data? Nowadays, users expects to have some kind of API Key. (Mandrill, Mailchimp, AWS and hundreds of other popular services just gives you ability to generate & control one or more _static_ api keys for your account). Is it possible to achieve this with DOT? 

Let me give you an use case for second question. There is a CRM application and user wants to download some of his data programmaticaly. With DOT (well its more oauth2 design) to achive this user would need to:
1. Somehow create and application on CRM side
2. Grab received client_id and client_secret
3. Write his code in a way it would be aware of the fact that tokens might expire in a middle of operation and handle this situation. This becomes a little bit harder than just "copy and paste your token in your code". 

How do you handle this case with DOT? Switching to simple Token Authentication is not a good idea – one will loose scopes limitation and other benefits. I'd really love to stay with OAuth2 for all our needs, but I'm confused with this 2 cases.

Thanks for help.

**Comment by pySilver** [comment]
anyone?

**Comment by kaiser0906** [comment]
Answer for #1, you don't have to create an application per user. One application will cover all the users.
For #2, Oauth does authentication. You need such an object level authorization such as entitlement or permissioning.
To use(access to) protected APIs, use access token(OAuth2).
To fetch protected data via the protected APIs, use either object level entitlement or permission.
