### ISSUE TITLE
POST /o/revoke_token/ should return status code 204, not 200

### ISSUE THREAD

**Issue by alexbecker** [evonove/django-oauth-toolkit#313]
Making a POST request to `/o/revoke_token/` currently returns a `200 - OK` response, but with no body. [RFC-7231](https://tools.ietf.org/html/rfc7231#section-6.3) indicates that the status code `204 - No Content` is preferable for this use case.

**Comment by outsbart** [comment]
Hi alexbecker, thanks for reporting this issue.

As much as I agree with you on the fact that empty responses should return 204 over 200 on empty response bodies, [RFC-7009](https://tools.ietf.org/html/rfc7009) explicitly indicates to return a 200 in section 2.2. For this reason, we are not changing the current behavior.
