### ISSUE TITLE
AuthorizationView.get overwrites the request object

### ISSUE THREAD

**Issue by alexbecker** [evonove/django-oauth-toolkit#315]
When a request is made to `/o/authorize`, the `AuthorizationView.get` function sets `kwargs['request']` at [L118](https://github.com/evonove/django-oauth-toolkit/blob/3960084db942a4b7f803ff94eb5b7cff0cef1c10/oauth2_provider/views/base.py#L118). This replaces the `WSGIRequest` object in the `RequestContext` object ultimately passed to the authorization template with an `oauthlib.Request` object, which does not have the same attributes to begin with and has not passed through the same middleware. This can break templates which use the missing attributes on the request object.

For some reason this issue only occurs for me with Django 1.8, possibly due to changes in template and template context processing.

If this is not intentional, then the fix is trivial. I would gladly submit such a PR since we have had to fork this project in order to work around this issue.

**Comment by poswald** [comment]
It looks like work was started on this here? https://github.com/evonove/django-oauth-toolkit/tree/fix-issue-315

Was there a reason this is not good to PR/merge yet?

**Comment by Psykopear** [comment]
@poswald Yes, it needs a test, I'm going to write it asap and merge the branch.

**Comment by mkjpryor-stfc** [comment]
Any progress on this issue? I am also being hit by this problem and will also need to fork the project to get around this.

**Comment by mkjpryor-stfc** [comment]
@Psykopear: I have merged these changes with master in my own fork - https://github.com/cedadev/django-oauth-toolkit/tree/fix-issue-315

What did you have in mind test-wise? It is not obvious to me how to test this... It obviously passes all the existing tests.

**Comment by Psykopear** [comment]
Merged in master, sorry it took so long guys.
