### ISSUE TITLE
Please help me understand why user is is required for authorize.

### ISSUE THREAD

**Issue by LiteWait** [evonove/django-oauth-toolkit#329]
I can't understand why the user id is bring required by the first part of o/authorize where it creates the Grant().  How can the consumer expect that the first call to o/authorize is an authenticated user?  I thought you are supplying the client_id which tells you which application you want to grant access too.  I am using a fork I was that adds the user and password to the authorize window.  It seems to me for single page apps (like ours) we can't expect the user to have logged in, right?

Please help me understand.

**Comment by LiteWait** [comment]
Maybe a better question, is there a way to combine (for Authorization Code Grant) the Authorization with the user and password?  Sites like LinkedIn and Twitter do this and it seems to make more sense as you can't make the assumption that the user is somehow logged in, and implementing it with a login page (really not workable for single-page apps) and then an authorization page seems clunky.

**Comment by poswald** [comment]
My understanding is that if you are writing your own web front-end to talk to your own backend (such that a user is presented with a username/password field they fill in) that you should be using:

- Resource Owner Password Credentials grant type
- Your own web site is the 'client' operating on behalf of the user
- This is a 'confidential' client with an id and secret that it uses when it passes the request along (and that the resource owner/user never sees)
- The website collects the username and password from the user and authenticates.
- In this flow, when trying to log in the user, you would be hitting the /o/token/ endpoint not the authorize one.

The Authorization Code Grant is used instead when you have a 3rd party web site that is requesting you to authenticate the user and pass them back the token (this is the redirection kind of flow that we often think of when doing oauth).
