### ISSUE TITLE
Problem with Application model migrations

### ISSUE THREAD

**Issue by jannon** [evonove/django-oauth-toolkit#336]
Migrations (like 0002) should separate out changes that deal with the Application model from changes that deal with other models.

If a project has always used a custom application model, the migration fails when trying to operate on the oauth2_provider_application table because it doesn't exist.  But such a project still needs the migration of the oauth2_provider_accesstoken table to remove the not null restriction from the user relation.

If this was split into two migrations, such a project could simply use `--fake` on the one with changes to the Application model and still run the migration with the AccessToken changes

**Comment by poswald** [comment]
Looking into this more, I just realized that I also have an app with this issue when upgrading to 0.10.0 now. I think that perhaps a workaround I had to add from a past migration is causing issues for me... I'm going to have to look into how to manually upgrade this one. I agree that changes in migrations need to be done extremely carefully. I'm not sure that this migration could be safely split now that it is released though. I agree in this case that the migrations should have been split. Closing this unless you have a more tangible suggestion on how to improve it now that it's released.

Perhaps using the [swappable model](https://github.com/wq/django-swappable-models) project can help going forward too.
