### ISSUE TITLE
RFC 7662 OAuth 2.0 Token Introspection

### ISSUE THREAD

**Issue by manelclos** [evonove/django-oauth-toolkit#342]
Is anyone working to add this to django-oauth-toolkit?

https://tools.ietf.org/html/rfc7662

**Comment by WouterSlob** [comment]
Any info about this?
I would also be interested in this functionality for our micro services architecture.

**Comment by jleclanche** [comment]
If someone wants to work on it, please go right ahead :)

**Comment by symptog** [comment]
Hi @jleclanche I'm not frightened implementing this feature and I've got some thoughts. Maybe you can give some advice.

1. Request Handling
  *  Creating a view that accepts a POST request and checks the token and respond with the defined JSON
  * Searching within the `ACCESS_TOKEN_MODEL` and return active status, scope, user, expire date
  * Protect the view using a `ReadWriteScopedResourceView` requiring the scope `introspection`
  * Therefor creating an Application and AccessToken for each Resource Server
  * OPTIONAL: Creating a Models and Views for Resource Servers and Scopes, so Resource Servers can create new Scopes and handle the AccessToken

2. Response Handling 
  * Hook into `validate_bearer_token`
  * Check for a setting `INTROSPECTION_URL` (should be `None` by default and not set on Authentication Server)
  * First check the Token against the local database if this fails send a request to `INTROSPECTION_URL`
  * On response check validity and create a Token in the local database with the provided information (Note: we don't have an Application)
  * Allow or Deny the Request

I don't know if creating Tokens this way will break the ProtectedResourceViews and REST-Framework integration.
