### ISSUE TITLE
Nonrel storages support

### ISSUE THREAD

**Issue by renanmartins-luizalabs** [evonove/django-oauth-toolkit#349]
I'm interested in this feature and I read in the README there's _help wanted_. What do you think is needed for this feature? I think we could create a `TokenStorage` interface. Is this the way to go?

**Comment by jleclanche** [comment]
I don't think that readme is really up to date to be honest. There seems to be very little enthusiasm around nonrel support so I don't really see it happening, unless someone steps up to do all the work and maintain it.

**Comment by jleclanche** [comment]
Closing per previous comment. This can be reopened if someone steps up.
