### ISSUE TITLE
Empty client_secret causes failure

### ISSUE THREAD

**Issue by poswald** [evonove/django-oauth-toolkit#353]
When using the password grant type with Resource Owner Password Credentials Grant, it can be the case where the `client_secret` isn't used.

In public apps like javascript and/or native apps, the `client_secret` cannot be kept secret by the client so it is just not issued/used. This means a request from `requests_oauthlib` would look something like:

```python
    oauth = OAuth2Session(client=LegacyApplicationClient(client_id='123'))

    token = oauth.fetch_token(
        token_url=ENDPOINT,
        username=username,
        password=password,
        client_id='123',
        #  client_secret='',  # Not sent
    )
```

This results in a request where the body looks like what you would get from:

    $ curl --form 'grant_type=password&username=USERNAME&password=PASSWORD' https://api.example.com/oauth/token/

The body looks like:

    u'username=myuser&password=hunter2&client_id=123456&grant_type=password'

Once we get into `oauthlib/oauth2/rfc6749/endpoints/token.py(91)create_token_response()` the response object is created. It has a `request.client_secret` of `None` here.

When it is compared in `_authenticate_request_body` and `_authenticate_basic_auth` the line from `oauth2_provider/oauth2_validators.py` is:

```python
    elif request.client.client_secret != client_secret:
```

This comparison fails because `''` and `None` are not equal. Something like this will work:

```python
    elif request.client.client_secret != (client_secret or '')
```

This will return a 401 with a `InvalidClientError`. 

Now, the convention in Django is that "NULL" charfields are `''` and not stored as `None`. I think in this case the underlying oauthlib is using `None` to represent 'missing data' so the above fix makes sense.

**Comment by poswald** [comment]
I am looking into adding a test for this but I can't reproduce it in the test case just yet. It may be sensitive to data or something. Looking into it some more...

**Comment by synasius** [comment]
@poswald I stumbled upon this issue too and I describe it here https://github.com/requests/requests-oauthlib/issues/227 

This is related to a bug in requests-oauthlib and I promised that I would submit a PR but I had no time recently.

**Comment by poswald** [comment]
Well that would certainly explain it. FWIW I agree with your analysis there too. I can look into sending a PR over there for it.

**Comment by synasius** [comment]
@poswald That would be great!

**Comment by esseti** [comment]
Is this fixed in the new version? i'm still using the 0.11 and it seems to have the same problem.
