### ISSUE TITLE
Triage of open issues

### ISSUE THREAD

**Issue by poswald** [evonove/django-oauth-toolkit#355]
Do you need help with triage? This seems like the best django/oauth2 library available there but it makes me a bit nervous to see so many open/unaddressed issues in an authentication library. I know oauth2 is complex but I think a lot of these are invalid and can be closed or need more info from the reporter.

Talking specifically about things like #293 and #318 and a few others which get opened and then it's hard to tell what needs to happen next. Users can't close issues so it's up to you to make a call on it.

**Comment by synasius** [comment]
@poswald your help is more than welcome! I'm adding you to the collaborators so you can start the triaging process.

**Comment by poswald** [comment]
Thank you.

**Comment by poswald** [comment]
Hm.. Is ability to close issues a separate permission in github (which is kind of necessary for triage)? I can only close my own right now it seems.

**Comment by synasius** [comment]
@poswald right! you need write permission
