### ISSUE TITLE
"error": "unsupported_grant_type"

### ISSUE THREAD

**Issue by qiailin** [evonove/django-oauth-toolkit#362]
when i  post the url 

http://127.0.0.1:8000/o/token?client_id=efhoQ6C6Q8LwncyMECgjv7HkfJu75uoZDdG2nYXD&client_secret=q5rj3i8ODV23boBmj17pp4RU8yYGVW8khWy5l9ToEajJTQ6NklctymlRHecLVajZjbY2tnwziQsI2lnIuUZKMUtXsfdyIRyu580SDxB9GVCLKIDfltjR7oVuMHPLSuof&grant_type=client-credentials

 "error": "unsupported_grant_type"

**Comment by poswald** [comment]
Try `grant_type=client_credentials` instead.The table stores `client-credentials` but the actual parameter in the OAuth spec is with an underscore. Also, while it will work this way you should put the client id and secret in the header via basic auth if you can.

**Comment by qiailin** [comment]
thanks
