### ISSUE TITLE
"error": "unsupported_grant_type"

### ISSUE THREAD

**Issue by qiailin** [evonove/django-oauth-toolkit#363]
when i  post this url 

http://127.0.0.1:8000/o/token?client_id=efhoQ6C6Q8LwncyMECgjv7HkfJu75uoZDdG2nYXD&client_secret=q5rj3i8ODV23boBmj17pp4RU8yYGVW8khWy5l9ToEajJTQ6NklctymlRHecLVajZjbY2tnwziQsI2lnIuUZKMUtXsfdyIRyu580SDxB9GVCLKIDfltjR7oVuMHPLSuof&grant_type=client-credentials

"error": "unsupported_grant_type"

**Comment by rodolphopivetta** [comment]
How did you fix this? I'm having the same problem.

**Comment by poswald** [comment]
The grant type should be `client_credentials` with an underscore. See [the spec for details](https://tools.ietf.org/html/rfc6749#section-4.4.2).
