### ISSUE TITLE
Always denied with valid client_credentials token for rest-framework extension

### ISSUE THREAD

**Issue by wirasto** [evonove/django-oauth-toolkit#369]
I use oauth to proect my api build with django-rest-framework. But when use client_credentials token always denied when access my resource.
I tried password token, everythin is fine...

**Comment by ilGuccio** [comment]
Same problem here

**Comment by ilGuccio** [comment]
I have this problem only in production environment, if I run app with runserver is fine

**Comment by ilGuccio** [comment]
@wirasto Take a look to this setting in you mod_wsgi configuration` WSGIPassAuthorization On`
Maybe the problem is Apache configuration

**Comment by wirasto** [comment]
I'm not use Apache. I run my rest-app with manage.py
`
$ python manage.py runserver`

**Comment by ilGuccio** [comment]
No idea without more information sorry

**Comment by wirasto** [comment]
It's ok. I didn't use client_credentials anymore :)

**Comment by poswald** [comment]
Glad it's working for you now. The `client_credentials` grant is pretty different than the `password` grant so its possible something was misconfigured. Feel free to reopen or open a new issue if you can pin down if it is a bug or a misconfiguration.

**Comment by wirasto** [comment]
Maybe just misconfigured :)

Just for information, the problem when use with django-rest-framework. without DRF is fine,,,
With and without DRF use same database,,,
