### ISSUE TITLE
{"error": "invalid_client"} in production environment

### ISSUE THREAD

**Issue by ilGuccio** [evonove/django-oauth-toolkit#371]
with:
curl -X POST -d "grant_type=client_credentials" -u"CHJgTtA66AcyNxOfk0BioDdlTMRog9QR3593upKI:Fv0hcW7F0d2yv3fNMbKFdMBkcTZ8dQHgJbtZpiVGlGi8NHTAoOyamdGCaQCQtImFpFzA3Nz6WMjXBg9BR5LwH4VQFNZzxUb9l4t2xfGcfaz2qt7ZHuxPTwfgexHDuJ82"  "********************.compute.amazonaws.com:8000/o/token/"

I obtain 
{"error": "invalid_client"}

If on VM I open port 8000, launch `python manage.py runserver 0.0.0.0:8000` and run 

curl -X POST -d curl -X POST -d "grant_type=client_credentials" -u"CHJgTtA66AcyNxOfk0BioDdlTMRog9QR3593upKI:Fv0hcW7F0d2yv3fNMbKFdMBkcTZ8dQHgJbtZpiVGlGi8NHTAoOyamdGCaQCQtImFpFzA3Nz6WMjXBg9BR5LwH4VQFNZzxUb9l4t2xfGcfaz2qt7ZHuxPTwfgexHDuJ82"  "http://****************.compute.amazonaws.com:8000/o/token/"

I obtain

{"access_token": "N8KVo9PNaBVKKh0nH4xoS5USM56gFq", "token_type": "Bearer", "expires_in": 36000, "scope": "read write"}

**Comment by ilGuccio** [comment]
Solved, apache issue. Need to set:
`WSGIPassAuthorization On`

**Comment by eikonomega** [comment]
Just for posterity sake, I wanted to mention that in my experience you have to restart the Apache service after making this change.
