### ISSUE TITLE
Way to configure  Access  from Create Application VIew.

### ISSUE THREAD

**Issue by f1shear** [evonove/django-oauth-toolkit#374]
https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/views/application.py#L20
Create Application  access   should be configurable  to staff or superuser or normal authenticated users. May be in settings file.

**Comment by poswald** [comment]
You can do this by extending the view and adding the permission required decorator. I agree that it may be nice to offer a way of setting this up. I'd maybe even go so far as to say this request could be handled as part of issue #196? If that covers it, then we can close this one as a duplicate.
