### ISSUE TITLE
Use a CharField for the `User` field in the "Edit application" form

### ISSUE THREAD

**Issue by db0company** [evonove/django-oauth-toolkit#376]
Being able to change the user who owns the application is great, but this page takes forever to load since it has to get the list of all the users to show them in the select dropdown. For this reason, I edit the applications using the django shell instead of this page.

Is there a way I can use a `forms.CharField` instead of the choices field in this form?

**Comment by michi88** [comment]
I think it shouldn't be there by default at all as it 'leaks' your User table

**Comment by db0company** [comment]
For future reference, here's how you can update something without loading the edit page:

```
from oauth2_provider import models
models.Application.objects.filter(id=1).update(redirect_uris='http://website.internet/redirect')
```

**Comment by teeberg** [comment]
I agree this has potential to become a major privacy problem if somebody uses this library and doesn't realize that they're exposing their whole user table.

**Comment by jleclanche** [comment]
Closing this per previous comments.

**Comment by michi88** [comment]
@jleclanche Which comments are you referring to? I don't quite understand why this is a 'wontfix'.

**Comment by michi88** [comment]
For anyone stumbling upon this, and as a suggestion, I think the view should not include the user field at all.

```python
from oauth2_provider import views
class NoUserApplicationUpdate(views.ApplicationUpdate):
    """
    View used to update an application owned by the request.user
    """
    def get_form_class(self):
        """
        Returns the form class for the application model
        """
        return modelform_factory(
            get_application_model(),
            fields=('name', 'client_id', 'client_secret', 'client_type',
                    'authorization_grant_type', 'redirect_uris',)
        )
```
I think this is a major security/privacy issue. If the views are intended as an example only this should be made more clear.

@jleclanche please comment on the reasoning for closing this.

Thanks!
