### ISSUE TITLE
Application creation

### ISSUE THREAD

**Issue by francescobtl** [evonove/django-oauth-toolkit#378]
Hello. I'm new to django and python, so excuse me if my questions are a bit stupid.

I've seen that the application creation form at /o/applications lets the user freely change client id, client secret and lets them select skip authorization. Isn't this dangerous? Or is it as intented and I havent really grasped the concept behind oauth2?

Eventually can i create an application programmatically?

**Comment by poswald** [comment]
Yes, you are correct that it is non-intuitive and arguably dangerous. Mapping the urls to that view in my opinion should not be encouraged in the documentation. Please see #196 for more discussion of it.
