### ISSUE TITLE
Login without password

### ISSUE THREAD

**Issue by nitinmeharia** [evonove/django-oauth-toolkit#380]
I'm also implementing mobile login. Here, from mobile(its uniquely mapped), I can get the user object. I'm verifying the OTP. Now I want to login this user without password. How can we achieve this?

**Comment by poswald** [comment]
[The google group](https://groups.google.com/forum/#!forum/django-oauth-toolkit) is a better place to ask questions about usage. You'll also need to provide more information about what you're doing.
