### ISSUE TITLE
dynamic redirect_uri match

### ISSUE THREAD

**Issue by molavy** [evonove/django-oauth-toolkit#381]
i have query param in redirect_uri like /q/1432/req/1
numbers is dynamic
how can set redirect_uri to handle dynamic parts

**Comment by poswald** [comment]
You should include more detail about which part you are having trouble with and discuss [in the forum](https://groups.google.com/forum/#!forum/django-oauth-toolkit). Dynamic parts of urls are usually handled via [Django's url dispatcher](https://docs.djangoproject.com/en/1.9/topics/http/urls/#named-groups)
