### ISSUE TITLE
Unique constraint on `RefreshToken.token`

### ISSUE THREAD

**Issue by jimgraham** [evonove/django-oauth-toolkit#382]
Hello.

Related to #377 

Is there a particular reason there is not a unique constraint on the `RefreshToken.token` field? In various places there is a `RefreshToken.objects.get(token=token)` (e.g. https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L377)

**Comment by kevin-brown** [comment]
I was looking through the models and notices that the following fields allow for non-unique values, which has the possibility of triggering errors on queries which expect them to be unique.

- [`Grant.code`](https://github.com/evonove/django-oauth-toolkit/blob/7cba4a5baa49005d449213b9738f427ceeb6af69/oauth2_provider/models.py#L152)
- [`AccessToken.token`](https://github.com/evonove/django-oauth-toolkit/blob/7cba4a5baa49005d449213b9738f427ceeb6af69/oauth2_provider/models.py#L190)
- [`RefreshToken.token`](https://github.com/evonove/django-oauth-toolkit/blob/7cba4a5baa49005d449213b9738f427ceeb6af69/oauth2_provider/models.py#L258)
