### ISSUE TITLE
Tox not included in requirements

### ISSUE THREAD

**Issue by jacktrades** [evonove/django-oauth-toolkit#388]
I tried to run the test suite, per the [instructions in the contributing section of the docs](https://django-oauth-toolkit.readthedocs.io/en/latest/contributing.html#run-the-tests), and realized that Tox was not listed in any of the requirements files.

Incidentally, and possibly unrelated, when I did install Tox (into the virtualenv) and run it, it threw a bunch of `could not install deps` errors.  I'm not all that familiar with Tox, so there's a good chance it's just user error, but I thought I'd throw it out there in case anyone has a quick solution.

**Comment by craigds** [comment]
Tox isn't required in the virtualenv; tox _manages_ the test virtualenvs.

So e.g. to run the test suite on a Mac:

```sudo pip install tox
cd django-oauth-toolkit
tox
```

Tox creates multiple virtualenvs for different versions of python etc and runs the tests in each of them.

**Comment by jacktrades** [comment]
Thanks @craigds that clears things up for me.  My problem with installing deps seemed to stem from an incompatible version of pip.  After fixing the pip issue, and removing the ([deprecated](https://testrun.org/tox/latest/config.html#confval-downloadcache=path)) `downloadcache` option, I was able to get the test suite to run.
