### ISSUE TITLE
Use cookies for authentication

### ISSUE THREAD

**Issue by sassanh** [evonove/django-oauth-toolkit#393]
Is it possible to make `django-oauth-toolkit` create a session and set `sessionid` cookie when user logs in? So that even without Authorization header and just with the cookie user can get resources like images by setting `src` attribute in `img` tag in his browser. I have a desktop application and a web application. It'd be great if my server could serve files like images that need to be served only to some special users. The django view (which is an drf api view) does an internal redirect to nginx, but in order to do the authorization I need to have the authenticated user in the view.

**Comment by ezheidtmann** [comment]
I'm interested in storing tokens in an `HttpOnly` cookie for reasons explained in this article: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

Has anyone built this for Django?

**Comment by jleclanche** [comment]
I'm kinda -1 on this. This sounds like some hefty scope creeping.

**Comment by ezheidtmann** [comment]
I tried to implement that strategy, but there are some significant problems (perhaps intractable) when your client is not on the same domain as the provider. In my app I've come back to storing tokens in localStorage. So I'm also -1 on including this in the toolkit; users can certainly implement the strategy by overriding appropriate parts of the toolkit.

For the OP's scenario, one solution could be including a token or time-based signature in the querystring for the image. This is trivial with s3 storage, for example.

**Comment by sassanh** [comment]
Yeah, s3 supports it but to achieve what s3 supports we need a bit customizing here. Is it documented how to customize the auth method so that it respects a get param?

**Comment by jleclanche** [comment]
Closing per comments.

**Comment by oscarychen** [comment]
> I'm interested in storing tokens in an `HttpOnly` cookie for reasons explained in this article: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage
> 
> Has anyone built this for Django?

I needed to store refresh token in a HttpOnly cookie, and send the access token back in response body.  Here is how I achieved this: https://github.com/oscarychen/django-oauth-toolkit-cookie-refresh
and then in my main project, I just install this repo, ie:
`pip install git+https://github.com/oscarychen/django-oauth-toolkit-cookie-refresh.git`

Disclaimer: this is still work-in-progress.
