### ISSUE TITLE
about the redirect_uri_allowed

### ISSUE THREAD

**Issue by lpig** [evonove/django-oauth-toolkit#404]
can I checks the redirect_uri just check the scheme and host not with the path.
I have many url in with the same host and I need to add it all in redirect_uris of the Application,can I just add the url host than all the url in this host can be allow?
thx..

**Comment by jleclanche** [comment]
You'll need to swap the model with your own and override `redirect_uri_allowed`. But this sounds like a security nightmare, I would *really* avoid doing this.

**Comment by lpig** [comment]
Yes, you are right, and I had already gave up to doing this. Thank for remind.
