### ISSUE TITLE
Cannot import IsAuthenticatedOrTokenHasScope

### ISSUE THREAD

**Issue by neequole** [evonove/django-oauth-toolkit#409]
Hi!

For some reason, I cannot import IsAuthenticatedOrTokenHasScope from  oauth2_provider.ext.rest_framework and per checking the source file, this class is missing (it only contains TokenHasScope, TokenHasReadWriteScope & TokenHasResourceScope). Fyi, I have installed it via pip3.5 install django-oauth-toolkit

**Comment by justinanderson** [comment]
IsAuthenticatedOrTokenHasScope was added by #396, but the latest release available via pip is 0.10.0 and only includes up to #322. You could use IsAuthenticatedOrTokenHasScope with 0.10.0 locally by copying it into your own project.

**Comment by neequole** [comment]
Thanks for the advice @justinanderson, this solved it!
