### ISSUE TITLE
how to protect post api

### ISSUE THREAD

**Issue by chenyanfun** [evonove/django-oauth-toolkit#412]
hi all:
I use the django-oauth-toolkit to authenticate my api ,but my api need to post request.I know if protect get-api I can use ProtectedResourceView.But if I use  ProtectedResourceView to my post-api,it's error to need cookie crsftoken.so what can I do for post-api.
I do not know whether articulated and look forward to everyone's help

**Comment by Girbons** [comment]
Hi @chenyanfun, 
Try to disable the csrf check:
```python
class ProtectedResourceView():
    
    @csrf_exempt
    def post(self):
        ...
```
https://docs.djangoproject.com/en/1.10/ref/csrf/#django.views.decorators.csrf.csrf_exempt
