### ISSUE TITLE
Open redirect vulnerability

### ISSUE THREAD

**Issue by keattang** [evonove/django-oauth-toolkit#413]
Currently, the default behaviour for the authorization view is to redirect to the the redirect_uri in the event of an error. This opens up the possibility for open redirects. 

A malicious user can create an application and set a redirect_uri to their malicious site. They can then give another user a link that could look like one of these:
`https://my.domain.com/oauth/authorize?client_id=[client_id]`
`https://my.domain.com/login?next=/oauth/authorize?client_id=[client_id]`

Both of these would result in an error causing the user to be redirected to the malicious site. I would suggest changing this default behaviour to redirect to an error page, similar to Google.

Please advise whether you intend to fix this.

**Comment by kevin-brown** [comment]
> Currently, the default behaviour for the authorization view is to redirect to the the redirect_uri in the event of an error.

I will note that, for most error cases, this is exactly what the OAuth 2 specification recommends.

The OAuth 2 specification only requires that errors are not redirected when the redirect URI is invalid, or when the client ID is invalid. [[4.1.2.1](https://tools.ietf.org/html/rfc6749#section-4.1.2.1)]

**Comment by keattang** [comment]
Interesting. Thanks for your response!
