### ISSUE TITLE
Wheel Support

### ISSUE THREAD

**Issue by kevin-brown** [evonove/django-oauth-toolkit#416]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [django-oauth-toolkit](https://pypi.python.org/pypi/django-oauth-toolkit), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install django-oauth-toolkit with just the wheel, without having to do any extra work.

**Comment by synasius** [comment]
Latest release is published as a wheel: https://github.com/evonove/django-oauth-toolkit/releases/tag/0.11.0
