### ISSUE TITLE
Default expiration time

### ISSUE THREAD

**Issue by LockonF** [evonove/django-oauth-toolkit#417]
The default expiration time for the token in settings.py is 36000 seconds, which translates to 10 hours.

Isn't the default timer supposed to be 3600 seconds (1 hour)?

**Comment by clintonb** [comment]
> Isn't the default timer supposed to be 3600 seconds (1 hour)?

According to what standard should the default be one hour?

**Comment by Psykopear** [comment]
The RFC does not suggest any default value, closing the issue.
