### ISSUE TITLE
Limiting the number of users for an Application

### ISSUE THREAD

**Issue by pobed2** [evonove/django-oauth-toolkit#419]
Hi there!

We're trying to implement a limit on the number of users that can have `AccessTokens` for a particular `Application` when using the `oauth2/token/` endpoint. This means adding a `user_limit` property to `Application` so it can be updated in the admin, and whenever a user tries to get a token, we validate that `count_users_that_user_app <= app.user_limit`.

Looking at `OAuth2Validator` and `OAuthLibCore`, I can't find the right place to check the number of users for the application before creating and returning an access token. We use the `authorization_code` and the `password` grants, which complicates things a bit. We also would like to return OAuth style error:

```
{
  "error": "invalid_client"
}
```

Any idea if there's a validator method or any other place that we can override to satisfy our needs?

Thank you!

**Comment by jleclanche** [comment]
With 52d2402d37ded038ad8a8083c641ef053cbfa07c, applications now have an `is_usable` method. You can override this to check for a user count, however you like. Let me know if it works!
