### ISSUE TITLE
oauth2 with channels

### ISSUE THREAD

**Issue by QAM** [evonove/django-oauth-toolkit#423]
I want to create websocket app with django channels.
However, I'm thinking how to integrate oauth2 with channels.
Right now, I think I can add modify oauth2_validator for channels' consumers.py "message".
Could I know is it a good solution?
Thank you

**Comment by Psykopear** [comment]
We are not working on django channels' integration at the moment, so can't help. Anyway we'd be glad to review any PR in the future if you find a good solution.
