### ISSUE TITLE
refresh token 

### ISSUE THREAD

**Issue by pawanvirsingh** [evonove/django-oauth-toolkit#432]
what is the inbuilt url for genrating acces_token from  refresh token in this package.

how can i generate a fresh access token  from my old refresh token  is there any url available or i have to make it custom.

**Comment by jleclanche** [comment]
See #351

**Comment by phillbaker** [comment]
To clarify, a request to the generic tokens endpoint like ([following the example](https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html#step-4-get-your-token-and-use-your-api)):

```
curl -X POST -d "grant_type=refresh_token&client_id=<client_id>&refresh_token=<refresh_token>"  http://localhost:8000/o/token/
```

should return a new access token for apps created the public client type. For private client apps, the client id/secret will likely need to be provided in the basic auth header.

**Comment by joelranjithjebanesan7** [comment]
this command shows invalid client error

**Comment by PharrellWANG** [comment]
@joelranjithjebanesan7 yes, same here. `{"error": "invalid_grant"}%`

Any clues to solve this problem?

**Comment by joelranjithjebanesan7** [comment]
I had generated new token and tried, it works.This may be using old token
instead of generating new one

**Comment by sachin87** [comment]
I am getting {"error": "unsupported_grant_type"} in response, what's wrong with my request.

**Comment by oma0256** [comment]
@sachin87 check to verify that you set your details correctly. For instance in my case my `client_id` was wrong.

**Comment by proteusvacuum** [comment]
You may have already solved this @sachin87 , but I came across this issue recently.
The 
```json
{ "error": "invalid_grant" } 
```
message is returned if the `refresh_token` you are using has been revoked or previously used. 

This message is raised in `oauthlib` here:

https://github.com/oauthlib/oauthlib/blob/d54965b86ce4ede956db70baff0b3d5e9182a007/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py#L113-L117

And is caused when `django-oauth-toolkit` returns `False` here: https://github.com/jazzband/django-oauth-toolkit/blob/9d2aac2480b2a1875eb52612661992f73606bade/oauth2_provider/oauth2_validators.py#L697-L707

It's a bit of a confusing error message for that outcome.
