### ISSUE TITLE
Allow wildcards in Application's redirect-uri field

### ISSUE THREAD

**Issue by tarzzz** [evonove/django-oauth-toolkit#443]
I am not sure if this is already supported (since I could not find it in docs).

Application's Redirect URIs should accept wildcard URIs (for sub-domains), and OAuth2 Validator should be able to validate the redirect_uri received in request against the redirect_uris entry in Application.

We should be able to add:

     Application.redirect_uris = '*.my-domain.com'

and this should be able to accept 'A.my-domain.com' in request's redirect_uri parameter.

I would be happy to make PR for this, if necessary.

**Comment by jleclanche** [comment]
Big -1 on wildcard support. However, the redirect uri validation should be exposed to the library users so that it can be overridden. I don't know if that's the case yet.

**Comment by tarzzz** [comment]
> the redirect uri validation should be exposed to the library users so that it can be overridden

This should also serve my purpose. Ideas on how we can implement it would be great..

**Comment by jleclanche** [comment]
@tarzzz i don't know off the top of my head. If you have a suggestion I'm willing to review it.

**Comment by tarzzz** [comment]
We have figured out a work-around for this for our application. I am going to close this issue, but can be opened if someone needs it..

Thanks @jleclanche anyways.. 😃

**Comment by jleclanche** [comment]
@tarzzz can you share the workaround, for the poor lad who's gonna end up in this issue off google a year from now? :)

**Comment by tarzzz** [comment]
@jleclanche: 
There wasn't a work around (pardon my language in my earlier comment). We simply decided to use another approach, which did not require wildcards/subdomains at all.

**Comment by jleclanche** [comment]
Alright, excellent. I don't think it's a particularly good idea to use wildcard redirect uris.

**Comment by samupl** [comment]
Actually, I've found an use-case where it might get useful. I'm trying to integrate OAuth2 based SSO login to a Plone application (don't even ask how I got into it:<).

Plone allows you to have multiple "Sites". They are located in different paths, for example:

* Site A is at http://example.com/A/
* Site B is at http://example.com/B/

Etc. Now for each site, I have to add another redirect URI. It would be helpful if I could just do:

`http://example.com/*/acl_users/oauth2`

**Comment by uroybd** [comment]
I agree with @samupl and I'm also trying to do something like this.

**Comment by aviars** [comment]
Supporting to RFC-8252 "OAuth2 for Native Apps" using PKCE would be a major upgrade to Django OAuth Toolkit.  I think @whytheplatypus  and @ekivemark  may have also explored solutions/workarounds.

**Comment by pheki** [comment]
The example on https://github.com/jazzband/django-oauth-toolkit/issues/443#issuecomment-420255286 doesn't work since validation has been moved to `clean()` on https://github.com/jazzband/django-oauth-toolkit/commit/96538876d0d7ea0319ba5286f9bde842a906e1c5, and `clean()` is not ideal to override as it also validates other fields
