### ISSUE TITLE
Documentation on templates

### ISSUE THREAD

**Issue by NBajanca** [evonove/django-oauth-toolkit#444]
Hello,

I've recently opened and closed issue #439.
This happened because I couldn't find any information on Templates.

Even though this can be solved by examining the template folder in the project I think some documentation on this, like [Django has for authentication](https://docs.djangoproject.com/en/1.10/topics/auth/default/#all-authentication-views) wouldn't hurt.

Let me know if this makes sense and I can write them.

**Comment by jleclanche** [comment]
Docs always welcome! Feel free to PR some.
