### ISSUE TITLE
Error on database migration using MariaDB 10.1

### ISSUE THREAD

**Issue by nathando** [evonove/django-oauth-toolkit#451]
The MariaDB by default use character set `uft8` (3 bytes version) and not `utf8mb4` (the 4 bytes version). This causes the problem if we store some 4 byte character. In order to switch to use character set `utf8mb4`. we can use specified list of parameters for mysqld below:
```--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-large-prefix=1 --innodb-file-format=barracuda```
and also set the `row_format=dynamic` for all the tables. Details for this is [here](https://mariadb.com/kb/en/mariadb/xtradbinnodb-storage-formats/) 

To set every table with row format is tedious. The latest version of development MariaDB, v10.2.2's solved this with an additional flag to set the [default row format](https://mariadb.com/kb/en/mariadb/xtradbinnodb-server-system-variables/#innodb_default_row_format). But this is not a stable release yet.

So meanwhile if we try to migrate on MariaDB with `utf8mb4` character set, the following error will occur:

```
Applying oauth2_provider.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  ...
    raise errorvalue
django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')
```

1. First solution:
There is a way to fix this: add Row_Format into migration script for the Table within this module. As Django's FAQ suggested [here](https://docs.djangoproject.com/en/1.10/faq/models/#how-do-i-add-database-specific-options-to-my-create-table-statements-such-as-specifying-myisam-as-the-table-type), it should be done as follow:
```
ALTER TABLE `tbl_name`  ROW_FORMAT=DYNAMIC;
```
2. Second solution: 
If we keep the **767 bytes** limit, the row_format can stay as **compact** (default value for MariaDB version<=10.2.1), then we gotta change all the columns with max_lengh=255 to 190 (which is <767/4) 

Which should be used as a temporary solution ?

**Comment by jleclanche** [comment]
You can try dropping the db_index for `client_secret` [here](https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/migrations/0001_initial.py#L27). It seems unnecessary anyway (secret shouldn't be indexed, only compared). I think that'll be enough but if it's not you can safely reduce the size of the token columns if you ensure the generated tokens are not longer than that.

My far more productive suggestion would be to switch to postgres, though. If that's possible for you, *seriously* consider it.

I'm closing this, although I'm not opposed to dropping the client_secret index if we double-check it won't have negative effects.

**Comment by nathando** [comment]
@jleclanche thank you for the quick and prompt reply! Will try that out! I am already using PostgreSQL actually. Just exploring mariadb for the clustering support.

**Comment by jleclanche** [comment]
Postgres is pretty good at that. Hit up #postgresql on freenode, the folks there are super friendly!
