### ISSUE TITLE
bytearray != unicode

### ISSUE THREAD

**Issue by indigodomo** [evonove/django-oauth-toolkit#461]
Using Python 2.7 and Django 1.9 and am seeing quite a few bytearrays being compared to unicode strings - which fails. oauth2_validators.py line 88 and 91, models.py line 130, and probably more. I suspect this is a Python 2.7 vs 3.x thing but I'm not positive. Wrapping the bytearray objects in unicode() seems to solve the problem.

**Comment by jleclanche** [comment]
Any chance you can write some tests for this?

**Comment by indigodomo** [comment]
Sorry, it was user error. Somehow my MySQL db had gotten set to use utf8_bin as the collation, so all strings coming out of the db were bytearrays. No clue how that got changed, but once fixed and the db recreated everything is humming along nicely.

**Comment by jleclanche** [comment]
Great!

I recommend using Postgres over mysql though if you're still in the planning phase (exactly to avoid inconsistencies like this).
