### ISSUE TITLE
Don't issue a token if the user.is_active = False

### ISSUE THREAD

**Issue by aidanlister** [evonove/django-oauth-toolkit#471]
It seems like nowhere is user.is_active checked,
https://github.com/evonove/django-oauth-toolkit/blob/86ef077dbbea5bc66df32c5273f7fdc728dc2791/oauth2_provider/backends.py

**Comment by dv321** [comment]
If you follow the call it looks like it happens here:
https://github.com/evonove/django-oauth-toolkit/blob/86ef077dbbea5bc66df32c5273f7fdc728dc2791/oauth2_provider/oauth2_validators.py#L412

**Comment by aidanlister** [comment]
Thanks Doug, not sure how I missed that or what modifications I've made which result in the user still getting a token.
