### ISSUE TITLE
Broken django-oauth-toolkit 0.10.0 uploaded to pypi?

### ISSUE THREAD

**Issue by xrmx** [evonove/django-oauth-toolkit#478]
Hello, for some reasons install django-oauth-toolkit==0.10.0 from pypi is not installing six, oauthlib and django-braces anymore. Any hint on what could be wrong?

**Comment by jleclanche** [comment]
Try upgrade setuptools before installing.

**Comment by xrmx** [comment]
Ah! Found the issue, it's an issue on installing other dependencies that makes the setup.py fails and then running the tests anyway. Sorry for the noise!
