### ISSUE TITLE
Custom user model with django-oauth-toolkit instead of User model of django.contrib.auth.models

### ISSUE THREAD

**Issue by narendra36** [evonove/django-oauth-toolkit#485]
Since django-oauth-toolkit uses the User model ofdjango.contrib.auth.models by default to track out the users for whom access token, refresh token will be created same for application creation. I want to create access token and refresh token for the users of my custom user model( custom user table). How can I achieve this using django-oauth-toolkit ?

**Comment by apallbox** [comment]
Since this question still have no answer: _you are feel free to use custom user model_.

Tokens are using `settings.AUTH_USER_MODEL` as user model in foreign keys so you can just add `AUTH_USER_MODEL = 'yourapp.User'` to your `settings.py` as Django docs says.

**Comment by narendra36** [comment]
Yes! I have solved it. Thanks for the answer. 👍

**Comment by MdStart** [comment]
I am facing issue while mapping django custom user to oauth toolkit . 
I get error {
    "error": "invalid_grant",
    "error_description": "Invalid credentials given."
}
while getting access token post user registration
though  superuser token access works fine. 

Need help!!!

**Comment by kamalmeh** [comment]
I am also getting the same error. Do you have any solution?
Please help.

**Comment by altairravus** [comment]
Encountered this problem today, the solution lies in Django's documentation--specifically on [this section](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project)

If you register your users through the admin panel, make sure to also import and register the UserAdmin as shown below.
```
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from .models import User

admin.site.register(User,UserAdmin)
```

cc: @kamalmeh @MdStart

**Comment by Rooseveltiny** [comment]
> I am also getting the same error. Do you have any solution?
> 
> Please help.

Have you got any solutions?

**Comment by Rooseveltiny** [comment]
Still same error. I've done all you said and nothing works.

**Comment by sanxchep** [comment]
is this done? or no one has figured out a way to add custom models to different oauth authentication module in the same project??

**Comment by Rooseveltiny** [comment]
I did it in my project about a half of a year earlier.


Пт, 19 авг. 2022 г. в 15:02, Sanxchep Sharma ***@***.***>:

**Comment by sanxchep** [comment]
Any snippets you can spare or link to the implementations??
thankss

**Comment by Rooseveltiny** [comment]
Okey. I give it too a bit later. I’ve got sources in my office.

Пт, 19 авг. 2022 г. в 15:15, Sanxchep Sharma ***@***.***>:

**Comment by sanxchep** [comment]
bro... did you find any??
i might get fired

**Comment by Rooseveltiny** [comment]
he-he. So well I've found sources. remind me what the concrete issue is? You'd like to create your own user class?

**Comment by sanxchep** [comment]
Yeahh, and custom config like expiration time to that particular auth
endpoint and stuff 😭😭

So sorry that I'm being desperate for it.... But been souring the internet
for some days now and didn't find it anywhere ... :((

**Comment by Rooseveltiny** [comment]
Well, each time to create a new django project it's a very good practice to declare your own user class in some kind of an app which is charged to perform authentication i.e. ecommerce_auth or some kind of. For that all you need is too create that extra app in your django project, and in models declare a user class using AbstractUser class to inherit your own user class from. 

`
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):...
'''
some custom methods and properties you are able to declare now
'''
`

then in your main settings of a project you should set a user class.
I have this one: 
`
AUTH_USER_MODEL = 'ecommerce_auth.User'
`

you may counter some issues if there was already default class used and data was created. 
for fixing it it's better to delete old data of default class and migrate a new declared class in your database. 

well I guess we could discuss that problem more concrete in telegram @Rooseveltiny if you wish. I don't remember quite well about some other nuances, but I suppose we could solute it while telegram texting.

**Comment by sanxchep** [comment]
yeah bro,
saved my ass
thankxx.
