### ISSUE TITLE
docs on pip out of date?

### ISSUE THREAD

**Issue by vsoch** [evonove/django-oauth-toolkit#486]
Just noticed that the docs [served at readthedocs](https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html) which are linked from [rest_framework]() are showing something that (might be?) out of date. For example, the instruction says to import from a submodule `ext`:

![image](https://user-images.githubusercontent.com/814322/27007767-dac3f4cc-4e2c-11e7-92b0-8987355417e6.png)

and I discovered the actual submodule is `contrib` (just from poking around site-packages), and I went to do a PR and... [you guys already fixed it](https://github.com/evonove/django-oauth-toolkit/blob/master/docs/rest-framework/getting_started.rst)

![image](https://user-images.githubusercontent.com/814322/27007775-1bd5cc60-4e2d-11e7-80bf-891333ab6ca6.png)

It looks like there is a silly error for some missing file that started about a [month ago](https://readthedocs.org/projects/django-oauth-toolkit/builds/). 

I'm totally loving this so far, btw! I'm still a little bit clunking around, but it's starting to make sense, heh.

**Comment by jleclanche** [comment]
@synasius any idea why the docs aren't updating?

**Comment by paulhtremblay** [comment]
Same here. Docs are out of date.

**Comment by JoshBroomberg** [comment]
+1 on this. Docs are still out of date on rest framework.

**Comment by jleclanche** [comment]
Closing for #553
