### ISSUE TITLE
[bug] dependency: pkg_resources.ContextualVersionConflict - requests

### ISSUE THREAD

**Issue by pypetey** [evonove/django-oauth-toolkit#488]
pkg_resources.ContextualVersionConflict:
(requests 2.12.5 (d:\projekty\a\env2\lib\site-packages), Requirement.parse('requests>=2.13.0'), {'django-oauth-toolkit'})

**Comment by jleclanche** [comment]
I'm guessing you have another package that requires `requests==2.12.5` and because of that, the DOT requests requirement conflicts.

Take a look at the other packages in your virtualenv.

**Comment by dhnesh** [comment]
pkg_resources.ContextualVersionConflict: (Django 1.10.5 (/home/ip-d/Documents/chris-weber/chrs_env/lib/python3.5/site-packages), Requirement.parse('django>=2.0'), {'django-oauth-toolkit'})

**Comment by Abunwer** [comment]
@dhnesh Django OAuth Toolkit requires Django version 2.0+, you should upgrade your Django version  <code> pip install django==2.0 <code>
