### ISSUE TITLE
migration in mysql 8.0.0 failed with 0005_auto_20170514_1141

### ISSUE THREAD

**Issue by GeniusWiki** [evonove/django-oauth-toolkit#492]
Running with docker MySQL 8.0.0,  migration failed at last script:

django.db.utils.OperationalError: (1833, "Cannot change column 'id': used in a foreign key constraint 'oauth2_provider_refr_access_token_id_775e84e8_fk_oauth2_pr' of table 'mydb.oauth2_provider_refreshtoken'")

**Comment by GeniusWiki** [comment]
just confirm docker mysql 8.0.1 doesn't have this issue!

**Comment by jleclanche** [comment]
MySQL issue, closing
