### ISSUE TITLE
Please update readthedocs.io

### ISSUE THREAD

**Issue by apiraino** [evonove/django-oauth-toolkit#499]
Hi,

I've noticed the online docs still mention to import `OAuth2Authentication` from `oauth2_provider.ext.rest_framework` instead of `oauth2_provider.contrib.rest_framework`.
It got me puzzled until I discovered that you simply moved the package.

Thanks,
Antonio

**Comment by YaxelPerez** [comment]
Yeah, also in the page for contributing it says to install dependencies from optional/requirements.txt instead of using tox.

**Comment by manelclos** [comment]
Please update.

**Comment by jleclanche** [comment]
Closing in favour of #506
