### ISSUE TITLE
How to define custom AccessToken and RefreshToken models?

### ISSUE THREAD

**Issue by GriMel** [evonove/django-oauth-toolkit#503]
Is it possible to customize these models? I have a UserProfile model (custom User model, defined in base config as AUTH_USER_MODEL) and special model for customers (in short - 2 separate models for system user and customers) I need to user Oauth2.0 for customers only but in this lib ForeignKey for user in AccessToken is hardcoded to be only settings.AUTH_USER_MODEL instance.
How to define custom AccessToken model for being used with this app and having FK in user to my Customers model?

**Comment by menecio** [comment]
Yes, you can swap AccessToken and RefreshToken the same way you can with the Application model
http://django-oauth-toolkit-latest.readthedocs.io/en/latest/advanced_topics.html#extending-the-application-model
