### ISSUE TITLE
Include required scopes in error response

### ISSUE THREAD

**Issue by simonschmidt** [evonove/django-oauth-toolkit#504]
To make it easier for a client to recover from a lack of scopes
it would be nice to get the required scopes back in the error response

Something like:

```http
HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "required_scopes": ["foo:write"],
  "detail": "You do not have permission to perform this action."
}
```

**Comment by menecio** [comment]
Refer to https://tools.ietf.org/html/rfc6749#section-4.1.2 

Revealing what scope is required doesn't sound like a good idea at all, you will reveal sensitive information.

**Comment by simonschmidt** [comment]
Fair enough, though I don't think the RFC applies as it is explicitly out of scope (section 4 does not apply, rather this would be under section 7.  Accessing Protected Resources)

Where it states:

> 7.2.  Error Response
>
> If a resource access request fails, the resource server SHOULD inform
> the client of the error.  While the specifics of such error responses
> are beyond the scope of this specification, this document establishes
> a common registry in Section 11.4 for error values to be shared among
> OAuth token authentication schemes.
> ...
