### ISSUE TITLE
How is it possible to gather the textual post of the person?

### ISSUE THREAD

**Issue by JafferWilson** [evonove/django-oauth-toolkit#511]
Hello,
I am working on the NLP project for statistics and social analysis of people based on textual contents.
I want to know how I can retrieve the text of post from the Facebook login person and perform my analysis process?

Please do reply.

**Comment by jleclanche** [comment]
This has nothing to do with this library.

**Comment by jleclanche** [comment]
Have a look at this or something: https://github.com/tschellenbach/Django-facebook

**Comment by JafferWilson** [comment]
Sure.. I will look at it. Thank you for your insights.
