### ISSUE TITLE
install_requires doesn't work for version 1.0.0 (tar.gz missing)

### ISSUE THREAD

**Issue by tovmeod** [evonove/django-oauth-toolkit#521]
If I run pip install django-oauth-toolkit==1.0.0 it downloads the wheel and works fine.

But if I add 'django-oauth-toolkit==1.0.0' to install_requires in setup.py of my project it complains:
Searching for django-oauth-toolkit==1.0.0
Reading https://pypi.python.org/simple/django-oauth-toolkit/
No local packages or working download links found for django-oauth-toolkit==1.0.0
error: Could not find suitable distribution for Requirement.parse('django-oauth-toolkit==1.0.0')

setup.py tries to get the tar.gz version.

it seems that the 1.0.0 version is missing the tar.gz, the last version available is 0.12.0

**Comment by jleclanche** [comment]
Make sure you have the latest version of pip/wheel/setuptools installed.

`pip install --upgrade pip wheel setuptools`.

I've gotten fed up with bugs in all three of those; Debian Jessie ships a stupidly ancient version of pip (1.5.2) which is the source of many issues like these.

Reopen if that's not it, but I'm willing to bet it is.

**Comment by tovmeod** [comment]
I currently have:
pip (9.0.1)
setuptools (36.6.0)
wheel (0.30.0)

In any case the pip install works, when running python setup.py test it fails
I can see https://pypi.python.org/simple/django-oauth-toolkit/ that the last version with tar.gz is 0.12.0, 1.0.0 doesn't have a tar.gz there, only wheel
Removing the specific django-oauth-toolkit version from setup.py works, but it installs 0.12.0

**Comment by jleclanche** [comment]
But a wheel should be just fine. Plenty of packages are wheel-only distributed. You just need `wheel` installed.

**Comment by tovmeod** [comment]
theoretically yes, it should be enough, but setup.py looks for a tar.gz.

I'm using 'python setup.py test', so I don't really have control over which kind of package it should use.
