### ISSUE TITLE
POST /o/introspect/ endpoint requires WRITE_SCOPE in addition to "introspection"

### ISSUE THREAD

**Issue by n2ygk** [evonove/django-oauth-toolkit#555]
POST /o/introspect/ returns a 403 when the scope of the access token only contains "introspection". Adding the WRITE_SCOPE value ("write") makes it succeed. This is because by default a POST is considered something requiring a WRITE_SCOPE in [views.mixins.ReadWriteScopedResourceMixin.dispatch](https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/views/mixins.py#L237-L242)

**Comment by n2ygk** [comment]
Here's the stack trace:

![trace](https://user-images.githubusercontent.com/4356471/36165959-2b5227c4-10bf-11e8-9ccb-f86030dfba93.png)

**Comment by symptog** [comment]
I interpreted the Introspection Endpoint as a resource so you can manage the clients (RS) within the AS itself.
Basically it's as `GET` request as we don't create any resources. Do you expect the behavior to be changed? I would be fine with this.

**Comment by n2ygk** [comment]
It's not a big deal. Just that an introspection POST is not in fact a write so shouldn't be checking for WRITE_SCOPE. So the ReadWriteSourceMixin is getting used somewhere where it shouldn't.

**Comment by symptog** [comment]
Yes you are right.
So we should use the `ScopedProtectedResourceView`?
