### ISSUE TITLE
Please update latest release to match tag 1.0.0

### ISSUE THREAD

**Issue by n2ygk** [evonove/django-oauth-toolkit#556]
@jleclanche @synasius: [Release 1.0.0 is what's in PyPi](https://pypi.python.org/pypi/django-oauth-toolkit) but the "latest" release in this github repo is `0.11.0` even though there are newer tags. Please sync this up if you can. I'd really appreciate the consistency!

**Comment by jleclanche** [comment]
Made the tag a release. https://github.com/evonove/django-oauth-toolkit/releases/tag/1.0.0
