### ISSUE TITLE
Grant type: All-in-one gives a "client is not authorized to use response_type token"

### ISSUE THREAD

**Issue by wezzynl** [evonove/django-oauth-toolkit#69]
When setting-up an Application with the "All-in-one generic" authorization grant type, I cannot make an authorization request with response_type of 'token' (or 'code' for that matter...)

Maybe I'm doing something wrong but It looks like the function 'validate_response_type' in 'oauth2_provider.oauth2_validators.py' doesn't take GRANT_ALLINONE into account?

**Comment by yarbelk** [comment]
+1 for this - I have a use case where I have a resource (tied to an ApplicationModel) that needs to be editable by a secure sever and public clients, with different scopes.  Permissions get really squirrly if I have to tie two Application instances with the two grant types to to the resource.  Some users can use one flow, some use another.

**Comment by jarcoal** [comment]
It would be really nice to see this supported.  I think that at some point most apps are going to need an Application that can support multiple flows.

Has anyone found a good work-around or is creating/maintaining 2+ applications the best way to go?

**Comment by jarussi** [comment]
Sorry for resurrecting a dead thread, but I also need this. Anyone found a solution / workaround for it?

**Comment by clintonb** [comment]
Any updates, @masci? What was the reason the all-in-one functionality was removed? Would you entertain reviewing/merging a restoration of similar functionality?

**Comment by clintonb** [comment]
@synasius @Girbons any interest in a PR restoring this functionality?

**Comment by jleclanche** [comment]
@clintonb If you can lay out a design doc + plan I can review that.

**Comment by clintonb** [comment]
@jleclanche no need. https://github.com/evonove/django-oauth-toolkit/pull/448 meets my needs, and should probably be suitable for others.

**Comment by jleclanche** [comment]
Cool, closing then.
