### ISSUE TITLE
Access Tokens that don't expire

### ISSUE THREAD

**Issue by jlhawn** [evonove/django-oauth-toolkit#93]
Is it currently possible to set it so that Access Tokens do not expire, and applications will no longer need the RefreshToken? Something like ACCESS_TOKEN_EXPIRE_SECONDS=None

I would like to make it so that tokens do not expire, but a resource owner can at any time choose to de-authorize an application (delete the access token). I believe this is how the Twitter API works as well: access tokens never expire, but are invalidated when a user explicitly rejects an application from their settings or the application is suspended by an admin.

**Comment by Psykopear** [comment]
We are closing this issue, as we agree with @samuelclay that expiring time can be set to a very high amount to solve this problem.
